//go:build tinygo

// Code generated by embedpb. DO NOT EDIT.
// Reflection-free, TinyGo-safe proto codec: hand-written protoiface.Methods
// keep google.golang.org/protobuf on its fast path (no reflect coder).
package proto

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"math"
	"sort"
	"strconv"
	"time"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

var _ = math.Float32bits
var _ = sort.Strings
var _ = fmt.Sprintf
var _ = bytes.Equal
var _ = strconv.AppendInt
var _ = base64.StdEncoding
var _ = time.Unix

type Direction int32

const (
	Direction_DIRECTION_UNKNOWN Direction = 0
	Direction_INGRESS           Direction = 1
	Direction_EGRESS            Direction = 2
)

var Direction_name = map[int32]string{
	0: "DIRECTION_UNKNOWN",
	1: "INGRESS",
	2: "EGRESS",
}

func (x Direction) String() string {
	if s, ok := Direction_name[int32(x)]; ok {
		return s
	}
	return fmt.Sprintf("Direction(%d)", int32(x))
}
func (x Direction) Enum() *Direction { p := new(Direction); *p = x; return p }

type Type int32

const (
	Type_TYPE_UNKNOWN Type = 0
	Type_TYPE_START   Type = 1
	Type_TYPE_END     Type = 2
	Type_TYPE_DROP    Type = 3
)

var Type_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "TYPE_START",
	2: "TYPE_END",
	3: "TYPE_DROP",
}

func (x Type) String() string {
	if s, ok := Type_name[int32(x)]; ok {
		return s
	}
	return fmt.Sprintf("Type(%d)", int32(x))
}
func (x Type) Enum() *Type { p := new(Type); *p = x; return p }

type isFlowFields_ConnectionInfo interface{ isFlowFields_ConnectionInfo() }
type FlowFields_PortInfo struct{ PortInfo *PortInfo }

func (*FlowFields_PortInfo) isFlowFields_ConnectionInfo() {}

type FlowFields_IcmpInfo struct{ IcmpInfo *ICMPInfo }

func (*FlowFields_IcmpInfo) isFlowFields_ConnectionInfo() {}

type FlowEvent struct {
	EventId       []byte
	Timestamp     *timestamppb.Timestamp
	PublicKey     []byte
	FlowFields    *FlowFields
	IsInitiator   bool
	unknownFields protoreflect.RawFields
}

func (m *FlowEvent) Reset()         { *m = FlowEvent{} }
func (m *FlowEvent) String() string { return fmt.Sprintf("FlowEvent{}") }
func (m *FlowEvent) ProtoMessage()  {}
func (m *FlowEvent) GetEventId() []byte {
	if m != nil {
		return m.EventId
	}
	return nil
}
func (m *FlowEvent) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}
func (m *FlowEvent) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}
func (m *FlowEvent) GetFlowFields() *FlowFields {
	if m != nil {
		return m.FlowFields
	}
	return nil
}
func (m *FlowEvent) GetIsInitiator() bool {
	if m != nil {
		return m.IsInitiator
	}
	return false
}

func (m *FlowEvent) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&FlowEvent{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *FlowEvent) sizeField() int {
	n := 0
	if len(m.EventId) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.EventId))
	}
	if m.Timestamp != nil {
		n += protowire.SizeTag(2) + protowire.SizeBytes(extSize_timestamppb_Timestamp(m.Timestamp))
	}
	if len(m.PublicKey) > 0 {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.PublicKey))
	}
	if m.FlowFields != nil {
		n += protowire.SizeTag(4) + protowire.SizeBytes(m.FlowFields.sizeField())
	}
	if m.IsInitiator {
		n += protowire.SizeTag(5) + protowire.SizeVarint(embedBool(m.IsInitiator))
	}
	n += len(m.unknownFields)
	return n
}

func (m *FlowEvent) marshalAppend(b []byte) ([]byte, error) {
	if len(m.EventId) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.EventId)
	}
	if m.Timestamp != nil {
		sub := extAppend_timestamppb_Timestamp(nil, m.Timestamp)
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if len(m.PublicKey) > 0 {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, m.PublicKey)
	}
	if m.FlowFields != nil {
		sub, _ := m.FlowFields.marshalAppend(nil)
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.IsInitiator {
		b = protowire.AppendTag(b, 5, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(m.IsInitiator))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *FlowEvent) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.EventId = append([]byte(nil), v...)
		case 2:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				m.Timestamp = extDecode_timestamppb_Timestamp(v)
			}
		case 3:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.PublicKey = append([]byte(nil), v...)
		case 4:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &FlowFields{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.FlowFields = mm
			}
		case 5:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.IsInitiator = v != 0
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *FlowEvent) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *FlowEvent) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"event_id\":"...)
	dst = jsonBytes(dst, m.EventId)
	dst = append(dst, ',')
	dst = append(dst, "\"timestamp\":"...)
	dst = extJSON_timestamppb_Timestamp(dst, m.Timestamp)
	dst = append(dst, ',')
	dst = append(dst, "\"public_key\":"...)
	dst = jsonBytes(dst, m.PublicKey)
	dst = append(dst, ',')
	dst = append(dst, "\"flow_fields\":"...)
	if m.FlowFields != nil {
		dst, err = m.FlowFields.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"isInitiator\":"...)
	dst = strconv.AppendBool(dst, m.IsInitiator)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type FlowEventAck struct {
	EventId       []byte
	IsInitiator   bool
	unknownFields protoreflect.RawFields
}

func (m *FlowEventAck) Reset()         { *m = FlowEventAck{} }
func (m *FlowEventAck) String() string { return fmt.Sprintf("FlowEventAck{}") }
func (m *FlowEventAck) ProtoMessage()  {}
func (m *FlowEventAck) GetEventId() []byte {
	if m != nil {
		return m.EventId
	}
	return nil
}
func (m *FlowEventAck) GetIsInitiator() bool {
	if m != nil {
		return m.IsInitiator
	}
	return false
}

func (m *FlowEventAck) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&FlowEventAck{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *FlowEventAck) sizeField() int {
	n := 0
	if len(m.EventId) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.EventId))
	}
	if m.IsInitiator {
		n += protowire.SizeTag(2) + protowire.SizeVarint(embedBool(m.IsInitiator))
	}
	n += len(m.unknownFields)
	return n
}

func (m *FlowEventAck) marshalAppend(b []byte) ([]byte, error) {
	if len(m.EventId) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.EventId)
	}
	if m.IsInitiator {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(m.IsInitiator))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *FlowEventAck) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.EventId = append([]byte(nil), v...)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.IsInitiator = v != 0
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *FlowEventAck) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *FlowEventAck) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"event_id\":"...)
	dst = jsonBytes(dst, m.EventId)
	dst = append(dst, ',')
	dst = append(dst, "\"isInitiator\":"...)
	dst = strconv.AppendBool(dst, m.IsInitiator)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type FlowFields struct {
	FlowId           []byte
	Type             Type
	RuleId           []byte
	Direction        Direction
	Protocol         uint32
	SourceIp         []byte
	DestIp           []byte
	ConnectionInfo   isFlowFields_ConnectionInfo
	RxPackets        uint64
	TxPackets        uint64
	RxBytes          uint64
	TxBytes          uint64
	SourceResourceId []byte
	DestResourceId   []byte
	unknownFields    protoreflect.RawFields
}

func (m *FlowFields) Reset()         { *m = FlowFields{} }
func (m *FlowFields) String() string { return fmt.Sprintf("FlowFields{}") }
func (m *FlowFields) ProtoMessage()  {}
func (m *FlowFields) GetFlowId() []byte {
	if m != nil {
		return m.FlowId
	}
	return nil
}
func (m *FlowFields) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type(0)
}
func (m *FlowFields) GetRuleId() []byte {
	if m != nil {
		return m.RuleId
	}
	return nil
}
func (m *FlowFields) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction(0)
}
func (m *FlowFields) GetProtocol() uint32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}
func (m *FlowFields) GetSourceIp() []byte {
	if m != nil {
		return m.SourceIp
	}
	return nil
}
func (m *FlowFields) GetDestIp() []byte {
	if m != nil {
		return m.DestIp
	}
	return nil
}
func (m *FlowFields) GetConnectionInfo() isFlowFields_ConnectionInfo {
	if m != nil {
		return m.ConnectionInfo
	}
	return nil
}
func (m *FlowFields) GetPortInfo() *PortInfo {
	if v, ok := m.GetConnectionInfo().(*FlowFields_PortInfo); ok {
		return v.PortInfo
	}
	return nil
}
func (m *FlowFields) GetIcmpInfo() *ICMPInfo {
	if v, ok := m.GetConnectionInfo().(*FlowFields_IcmpInfo); ok {
		return v.IcmpInfo
	}
	return nil
}
func (m *FlowFields) GetRxPackets() uint64 {
	if m != nil {
		return m.RxPackets
	}
	return 0
}
func (m *FlowFields) GetTxPackets() uint64 {
	if m != nil {
		return m.TxPackets
	}
	return 0
}
func (m *FlowFields) GetRxBytes() uint64 {
	if m != nil {
		return m.RxBytes
	}
	return 0
}
func (m *FlowFields) GetTxBytes() uint64 {
	if m != nil {
		return m.TxBytes
	}
	return 0
}
func (m *FlowFields) GetSourceResourceId() []byte {
	if m != nil {
		return m.SourceResourceId
	}
	return nil
}
func (m *FlowFields) GetDestResourceId() []byte {
	if m != nil {
		return m.DestResourceId
	}
	return nil
}

func (m *FlowFields) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&FlowFields{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *FlowFields) sizeField() int {
	n := 0
	if len(m.FlowId) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.FlowId))
	}
	if m.Type != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(int64(m.Type)))
	}
	if len(m.RuleId) > 0 {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.RuleId))
	}
	if m.Direction != 0 {
		n += protowire.SizeTag(4) + protowire.SizeVarint(uint64(int64(m.Direction)))
	}
	if m.Protocol != 0 {
		n += protowire.SizeTag(5) + protowire.SizeVarint(uint64(m.Protocol))
	}
	if len(m.SourceIp) > 0 {
		n += protowire.SizeTag(6) + protowire.SizeBytes(len(m.SourceIp))
	}
	if len(m.DestIp) > 0 {
		n += protowire.SizeTag(7) + protowire.SizeBytes(len(m.DestIp))
	}
	switch c := m.ConnectionInfo.(type) {
	case *FlowFields_PortInfo:
		_ = c
		n += protowire.SizeTag(8) + protowire.SizeBytes(c.PortInfo.sizeField())
	case *FlowFields_IcmpInfo:
		_ = c
		n += protowire.SizeTag(9) + protowire.SizeBytes(c.IcmpInfo.sizeField())
	}
	if m.RxPackets != 0 {
		n += protowire.SizeTag(10) + protowire.SizeVarint(m.RxPackets)
	}
	if m.TxPackets != 0 {
		n += protowire.SizeTag(11) + protowire.SizeVarint(m.TxPackets)
	}
	if m.RxBytes != 0 {
		n += protowire.SizeTag(12) + protowire.SizeVarint(m.RxBytes)
	}
	if m.TxBytes != 0 {
		n += protowire.SizeTag(13) + protowire.SizeVarint(m.TxBytes)
	}
	if len(m.SourceResourceId) > 0 {
		n += protowire.SizeTag(14) + protowire.SizeBytes(len(m.SourceResourceId))
	}
	if len(m.DestResourceId) > 0 {
		n += protowire.SizeTag(15) + protowire.SizeBytes(len(m.DestResourceId))
	}
	n += len(m.unknownFields)
	return n
}

func (m *FlowFields) marshalAppend(b []byte) ([]byte, error) {
	if len(m.FlowId) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.FlowId)
	}
	if m.Type != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.Type)))
	}
	if len(m.RuleId) > 0 {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, m.RuleId)
	}
	if m.Direction != 0 {
		b = protowire.AppendTag(b, 4, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.Direction)))
	}
	if m.Protocol != 0 {
		b = protowire.AppendTag(b, 5, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Protocol))
	}
	if len(m.SourceIp) > 0 {
		b = protowire.AppendTag(b, 6, protowire.BytesType)
		b = protowire.AppendBytes(b, m.SourceIp)
	}
	if len(m.DestIp) > 0 {
		b = protowire.AppendTag(b, 7, protowire.BytesType)
		b = protowire.AppendBytes(b, m.DestIp)
	}
	switch c := m.ConnectionInfo.(type) {
	case *FlowFields_PortInfo:
		sub, _ := c.PortInfo.marshalAppend(nil)
		b = protowire.AppendTag(b, 8, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	case *FlowFields_IcmpInfo:
		sub, _ := c.IcmpInfo.marshalAppend(nil)
		b = protowire.AppendTag(b, 9, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.RxPackets != 0 {
		b = protowire.AppendTag(b, 10, protowire.VarintType)
		b = protowire.AppendVarint(b, m.RxPackets)
	}
	if m.TxPackets != 0 {
		b = protowire.AppendTag(b, 11, protowire.VarintType)
		b = protowire.AppendVarint(b, m.TxPackets)
	}
	if m.RxBytes != 0 {
		b = protowire.AppendTag(b, 12, protowire.VarintType)
		b = protowire.AppendVarint(b, m.RxBytes)
	}
	if m.TxBytes != 0 {
		b = protowire.AppendTag(b, 13, protowire.VarintType)
		b = protowire.AppendVarint(b, m.TxBytes)
	}
	if len(m.SourceResourceId) > 0 {
		b = protowire.AppendTag(b, 14, protowire.BytesType)
		b = protowire.AppendBytes(b, m.SourceResourceId)
	}
	if len(m.DestResourceId) > 0 {
		b = protowire.AppendTag(b, 15, protowire.BytesType)
		b = protowire.AppendBytes(b, m.DestResourceId)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *FlowFields) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.FlowId = append([]byte(nil), v...)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Type = Type(v)
		case 3:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.RuleId = append([]byte(nil), v...)
		case 4:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Direction = Direction(v)
		case 5:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Protocol = uint32(v)
		case 6:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.SourceIp = append([]byte(nil), v...)
		case 7:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.DestIp = append([]byte(nil), v...)
		case 8:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *PortInfo
				mm := &PortInfo{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.ConnectionInfo = &FlowFields_PortInfo{PortInfo: mv}
			}
		case 9:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *ICMPInfo
				mm := &ICMPInfo{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.ConnectionInfo = &FlowFields_IcmpInfo{IcmpInfo: mv}
			}
		case 10:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.RxPackets = v
		case 11:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.TxPackets = v
		case 12:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.RxBytes = v
		case 13:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.TxBytes = v
		case 14:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.SourceResourceId = append([]byte(nil), v...)
		case 15:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.DestResourceId = append([]byte(nil), v...)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *FlowFields) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *FlowFields) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"flow_id\":"...)
	dst = jsonBytes(dst, m.FlowId)
	dst = append(dst, ',')
	dst = append(dst, "\"type\":"...)
	if s, ok := Type_name[int32(m.Type)]; ok {
		dst = jsonString(dst, s)
	} else {
		dst = strconv.AppendInt(dst, int64(m.Type), 10)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"rule_id\":"...)
	dst = jsonBytes(dst, m.RuleId)
	dst = append(dst, ',')
	dst = append(dst, "\"direction\":"...)
	if s, ok := Direction_name[int32(m.Direction)]; ok {
		dst = jsonString(dst, s)
	} else {
		dst = strconv.AppendInt(dst, int64(m.Direction), 10)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"protocol\":"...)
	dst = strconv.AppendUint(dst, uint64(m.Protocol), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"source_ip\":"...)
	dst = jsonBytes(dst, m.SourceIp)
	dst = append(dst, ',')
	dst = append(dst, "\"dest_ip\":"...)
	dst = jsonBytes(dst, m.DestIp)
	dst = append(dst, ',')
	switch c := m.ConnectionInfo.(type) {
	case *FlowFields_PortInfo:
		dst = append(dst, "\"port_info\":"...)
		if c.PortInfo != nil {
			dst, err = c.PortInfo.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	case *FlowFields_IcmpInfo:
		dst = append(dst, "\"icmp_info\":"...)
		if c.IcmpInfo != nil {
			dst, err = c.IcmpInfo.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	}
	dst = append(dst, "\"rx_packets\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendUint(dst, uint64(m.RxPackets), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"tx_packets\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendUint(dst, uint64(m.TxPackets), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"rx_bytes\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendUint(dst, uint64(m.RxBytes), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"tx_bytes\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendUint(dst, uint64(m.TxBytes), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"source_resource_id\":"...)
	dst = jsonBytes(dst, m.SourceResourceId)
	dst = append(dst, ',')
	dst = append(dst, "\"dest_resource_id\":"...)
	dst = jsonBytes(dst, m.DestResourceId)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type ICMPInfo struct {
	IcmpType      uint32
	IcmpCode      uint32
	unknownFields protoreflect.RawFields
}

func (m *ICMPInfo) Reset()         { *m = ICMPInfo{} }
func (m *ICMPInfo) String() string { return fmt.Sprintf("ICMPInfo{}") }
func (m *ICMPInfo) ProtoMessage()  {}
func (m *ICMPInfo) GetIcmpType() uint32 {
	if m != nil {
		return m.IcmpType
	}
	return 0
}
func (m *ICMPInfo) GetIcmpCode() uint32 {
	if m != nil {
		return m.IcmpCode
	}
	return 0
}

func (m *ICMPInfo) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&ICMPInfo{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *ICMPInfo) sizeField() int {
	n := 0
	if m.IcmpType != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(m.IcmpType))
	}
	if m.IcmpCode != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.IcmpCode))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ICMPInfo) marshalAppend(b []byte) ([]byte, error) {
	if m.IcmpType != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.IcmpType))
	}
	if m.IcmpCode != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.IcmpCode))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *ICMPInfo) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.IcmpType = uint32(v)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.IcmpCode = uint32(v)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *ICMPInfo) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *ICMPInfo) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"icmp_type\":"...)
	dst = strconv.AppendUint(dst, uint64(m.IcmpType), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"icmp_code\":"...)
	dst = strconv.AppendUint(dst, uint64(m.IcmpCode), 10)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type PortInfo struct {
	SourcePort    uint32
	DestPort      uint32
	unknownFields protoreflect.RawFields
}

func (m *PortInfo) Reset()         { *m = PortInfo{} }
func (m *PortInfo) String() string { return fmt.Sprintf("PortInfo{}") }
func (m *PortInfo) ProtoMessage()  {}
func (m *PortInfo) GetSourcePort() uint32 {
	if m != nil {
		return m.SourcePort
	}
	return 0
}
func (m *PortInfo) GetDestPort() uint32 {
	if m != nil {
		return m.DestPort
	}
	return 0
}

func (m *PortInfo) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&PortInfo{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *PortInfo) sizeField() int {
	n := 0
	if m.SourcePort != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(m.SourcePort))
	}
	if m.DestPort != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.DestPort))
	}
	n += len(m.unknownFields)
	return n
}

func (m *PortInfo) marshalAppend(b []byte) ([]byte, error) {
	if m.SourcePort != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.SourcePort))
	}
	if m.DestPort != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.DestPort))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *PortInfo) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.SourcePort = uint32(v)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.DestPort = uint32(v)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *PortInfo) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *PortInfo) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"source_port\":"...)
	dst = strconv.AppendUint(dst, uint64(m.SourcePort), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"dest_port\":"...)
	dst = strconv.AppendUint(dst, uint64(m.DestPort), 10)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

func extSize_timestamppb_Timestamp(v *timestamppb.Timestamp) int {
	if v == nil {
		return 0
	}
	n := 0
	if v.Seconds != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(v.Seconds))
	}
	if v.Nanos != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(int64(v.Nanos)))
	}
	return n
}
func extAppend_timestamppb_Timestamp(b []byte, v *timestamppb.Timestamp) []byte {
	if v == nil {
		return b
	}
	if v.Seconds != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(v.Seconds))
	}
	if v.Nanos != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(v.Nanos)))
	}
	return b
}
func extDecode_timestamppb_Timestamp(b []byte) *timestamppb.Timestamp {
	m := &timestamppb.Timestamp{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Seconds = int64(v)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Nanos = int32(v)
		default:
			consumed = protowire.ConsumeFieldValue(num, typ, b)
		}
		if consumed < 0 {
			break
		}
		b = b[consumed:]
	}
	return m
}
func extJSON_timestamppb_Timestamp(dst []byte, v *timestamppb.Timestamp) []byte {
	if v == nil {
		return append(dst, "null"...)
	}
	t := time.Unix(v.Seconds, int64(v.Nanos)).UTC()
	dst = append(dst, '"')
	dst = t.AppendFormat(dst, "2006-01-02T15:04:05")
	if v.Nanos != 0 {
		dst = append(dst, '.')
		dst = append(dst, jsonNanoFrac(v.Nanos)...)
	}
	dst = append(dst, 'Z', '"')
	return dst
}

func embedBool(v bool) uint64 {
	if v {
		return 1
	}
	return 0
}

type msgReflect struct {
	marshal    func([]byte) ([]byte, error)
	size       func() int
	unmarshal  func([]byte) error
	iface      protoreflect.ProtoMessage
	valid      bool
	newFn      func() protoreflect.Message
	getUnknown func() protoreflect.RawFields
	setUnknown func(protoreflect.RawFields)
}

var _ protoreflect.Message = msgReflect{}

func (r msgReflect) ProtoMethods() *protoiface.Methods    { return &embedMethods }
func (r msgReflect) Interface() protoreflect.ProtoMessage { return r.iface }
func (r msgReflect) IsValid() bool                        { return r.valid }
func (r msgReflect) New() protoreflect.Message            { return r.newFn() }
func (r msgReflect) GetUnknown() protoreflect.RawFields   { return r.getUnknown() }
func (r msgReflect) SetUnknown(f protoreflect.RawFields)  { r.setUnknown(f) }

func embedCanary(m string) string {
	return "CANARY: protoreflect.Message." + m + " called on reflection-free message"
}

func (r msgReflect) Descriptor() protoreflect.MessageDescriptor { panic(embedCanary("Descriptor")) }
func (r msgReflect) Type() protoreflect.MessageType             { panic(embedCanary("Type")) }
func (r msgReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(embedCanary("Range"))
}
func (r msgReflect) Has(protoreflect.FieldDescriptor) bool               { panic(embedCanary("Has")) }
func (r msgReflect) Clear(protoreflect.FieldDescriptor)                  { panic(embedCanary("Clear")) }
func (r msgReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value { panic(embedCanary("Get")) }
func (r msgReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(embedCanary("Set"))
}
func (r msgReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(embedCanary("Mutable"))
}
func (r msgReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(embedCanary("NewField"))
}
func (r msgReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(embedCanary("WhichOneof"))
}

var embedMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: in.Message.(msgReflect).size()}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		b, err := in.Message.(msgReflect).marshal(in.Buf)
		return protoiface.MarshalOutput{Buf: b}, err
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := in.Message.(msgReflect).unmarshal(in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		src := in.Source.(msgReflect)
		dst := in.Destination.(msgReflect)
		sb, _ := src.marshal(nil)
		if err := dst.unmarshal(sb); err != nil {
			return protoiface.MergeOutput{}
		}
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(in protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		a, ok1 := in.MessageA.(msgReflect)
		b, ok2 := in.MessageB.(msgReflect)
		if !ok1 || !ok2 {
			return protoiface.EqualOutput{Equal: false}
		}
		ab, _ := a.marshal(nil)
		bb, _ := b.marshal(nil)
		return protoiface.EqualOutput{Equal: bytes.Equal(ab, bb)}
	},
}

// --- protojson-compatible JSON helpers ---

func jsonEndObj(dst []byte) []byte {
	if n := len(dst); n > 0 && dst[n-1] == ',' {
		dst[n-1] = '}'
		return dst
	}
	return append(dst, '}')
}

func jsonHexDigit(b byte) byte {
	if b < 10 {
		return '0' + b
	}
	return 'a' + b - 10
}

func jsonString(dst []byte, s string) []byte {
	dst = append(dst, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '"':
			dst = append(dst, '\\', '"')
		case '\\':
			dst = append(dst, '\\', '\\')
		case '\n':
			dst = append(dst, '\\', 'n')
		case '\r':
			dst = append(dst, '\\', 'r')
		case '\t':
			dst = append(dst, '\\', 't')
		default:
			if c < 0x20 {
				dst = append(dst, '\\', 'u', '0', '0', jsonHexDigit(c>>4), jsonHexDigit(c&0xf))
			} else {
				dst = append(dst, c)
			}
		}
	}
	return append(dst, '"')
}

func jsonBytes(dst []byte, b []byte) []byte {
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, b)
	return append(dst, '"')
}

// jsonNanoFrac formats sub-second nanos as protojson does: trailing zero groups
// of three trimmed, leaving 3, 6, or 9 fractional digits.
func jsonNanoFrac(nanos int32) string {
	buf := fmt.Sprintf("%09d", nanos)
	n := 9
	for n > 3 && buf[n-1] == '0' && buf[n-2] == '0' && buf[n-3] == '0' {
		n -= 3
	}
	return buf[:n]
}
