// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target flow; DO NOT EDIT.

//go:build tinygo

package proto

import (
	"bytes"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type flowEventReflect struct{ m *FlowEvent }
type flowEventAckReflect struct{ m *FlowEventAck }
type flowFieldsReflect struct{ m *FlowFields }
type portInfoReflect struct{ m *PortInfo }
type iCMPInfoReflect struct{ m *ICMPInfo }

func protoCanary(method string) string {
	return "flow proto fast-path: unexpected protoreflect.Message." + method
}

func (r flowEventReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r flowEventReflect) Type() protoreflect.MessageType       { panic(protoCanary("Type")) }
func (r flowEventReflect) New() protoreflect.Message            { return flowEventReflect{m: new(FlowEvent)} }
func (r flowEventReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r flowEventReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r flowEventReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r flowEventReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r flowEventReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r flowEventReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r flowEventReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r flowEventReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r flowEventReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r flowEventReflect) GetUnknown() protoreflect.RawFields { return r.m.unknownFields }
func (r flowEventReflect) SetUnknown(f protoreflect.RawFields) {
	r.m.unknownFields = append(r.m.unknownFields[:0], f...)
}
func (r flowEventReflect) IsValid() bool                     { return r.m != nil }
func (r flowEventReflect) ProtoMethods() *protoiface.Methods { return &flowEventMethods }

func (r flowEventAckReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r flowEventAckReflect) Type() protoreflect.MessageType { panic(protoCanary("Type")) }
func (r flowEventAckReflect) New() protoreflect.Message {
	return flowEventAckReflect{m: new(FlowEventAck)}
}
func (r flowEventAckReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r flowEventAckReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r flowEventAckReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r flowEventAckReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r flowEventAckReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r flowEventAckReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r flowEventAckReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r flowEventAckReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r flowEventAckReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r flowEventAckReflect) GetUnknown() protoreflect.RawFields { return r.m.unknownFields }
func (r flowEventAckReflect) SetUnknown(f protoreflect.RawFields) {
	r.m.unknownFields = append(r.m.unknownFields[:0], f...)
}
func (r flowEventAckReflect) IsValid() bool                     { return r.m != nil }
func (r flowEventAckReflect) ProtoMethods() *protoiface.Methods { return &flowEventAckMethods }

func (r flowFieldsReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r flowFieldsReflect) Type() protoreflect.MessageType       { panic(protoCanary("Type")) }
func (r flowFieldsReflect) New() protoreflect.Message            { return flowFieldsReflect{m: new(FlowFields)} }
func (r flowFieldsReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r flowFieldsReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r flowFieldsReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r flowFieldsReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r flowFieldsReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r flowFieldsReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r flowFieldsReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r flowFieldsReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r flowFieldsReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r flowFieldsReflect) GetUnknown() protoreflect.RawFields { return r.m.unknownFields }
func (r flowFieldsReflect) SetUnknown(f protoreflect.RawFields) {
	r.m.unknownFields = append(r.m.unknownFields[:0], f...)
}
func (r flowFieldsReflect) IsValid() bool                     { return r.m != nil }
func (r flowFieldsReflect) ProtoMethods() *protoiface.Methods { return &flowFieldsMethods }

func (r portInfoReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r portInfoReflect) Type() protoreflect.MessageType       { panic(protoCanary("Type")) }
func (r portInfoReflect) New() protoreflect.Message            { return portInfoReflect{m: new(PortInfo)} }
func (r portInfoReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r portInfoReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r portInfoReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r portInfoReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r portInfoReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r portInfoReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r portInfoReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r portInfoReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r portInfoReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r portInfoReflect) GetUnknown() protoreflect.RawFields { return r.m.unknownFields }
func (r portInfoReflect) SetUnknown(f protoreflect.RawFields) {
	r.m.unknownFields = append(r.m.unknownFields[:0], f...)
}
func (r portInfoReflect) IsValid() bool                     { return r.m != nil }
func (r portInfoReflect) ProtoMethods() *protoiface.Methods { return &portInfoMethods }

func (r iCMPInfoReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r iCMPInfoReflect) Type() protoreflect.MessageType       { panic(protoCanary("Type")) }
func (r iCMPInfoReflect) New() protoreflect.Message            { return iCMPInfoReflect{m: new(ICMPInfo)} }
func (r iCMPInfoReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r iCMPInfoReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r iCMPInfoReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r iCMPInfoReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r iCMPInfoReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r iCMPInfoReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r iCMPInfoReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r iCMPInfoReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r iCMPInfoReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r iCMPInfoReflect) GetUnknown() protoreflect.RawFields { return r.m.unknownFields }
func (r iCMPInfoReflect) SetUnknown(f protoreflect.RawFields) {
	r.m.unknownFields = append(r.m.unknownFields[:0], f...)
}
func (r iCMPInfoReflect) IsValid() bool                     { return r.m != nil }
func (r iCMPInfoReflect) ProtoMethods() *protoiface.Methods { return &iCMPInfoMethods }

var flowEventMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeFlowEvent(in.Message.(flowEventReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalFlowEvent(in.Buf, in.Message.(flowEventReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalFlowEvent(in.Message.(flowEventReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeFlowEvent(in.Destination.(flowEventReflect).m, in.Source.(flowEventReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalFlowEvent(in.MessageA.(flowEventReflect).m, in.MessageB.(flowEventReflect).m)}
	},
}

var flowEventAckMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeFlowEventAck(in.Message.(flowEventAckReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalFlowEventAck(in.Buf, in.Message.(flowEventAckReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalFlowEventAck(in.Message.(flowEventAckReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeFlowEventAck(in.Destination.(flowEventAckReflect).m, in.Source.(flowEventAckReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalFlowEventAck(in.MessageA.(flowEventAckReflect).m, in.MessageB.(flowEventAckReflect).m)}
	},
}

var flowFieldsMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeFlowFields(in.Message.(flowFieldsReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalFlowFields(in.Buf, in.Message.(flowFieldsReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalFlowFields(in.Message.(flowFieldsReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeFlowFields(in.Destination.(flowFieldsReflect).m, in.Source.(flowFieldsReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalFlowFields(in.MessageA.(flowFieldsReflect).m, in.MessageB.(flowFieldsReflect).m)}
	},
}

var portInfoMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizePortInfo(in.Message.(portInfoReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalPortInfo(in.Buf, in.Message.(portInfoReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalPortInfo(in.Message.(portInfoReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergePortInfo(in.Destination.(portInfoReflect).m, in.Source.(portInfoReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalPortInfo(in.MessageA.(portInfoReflect).m, in.MessageB.(portInfoReflect).m)}
	},
}

var iCMPInfoMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeICMPInfo(in.Message.(iCMPInfoReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalICMPInfo(in.Buf, in.Message.(iCMPInfoReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalICMPInfo(in.Message.(iCMPInfoReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeICMPInfo(in.Destination.(iCMPInfoReflect).m, in.Source.(iCMPInfoReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalICMPInfo(in.MessageA.(iCMPInfoReflect).m, in.MessageB.(iCMPInfoReflect).m)}
	},
}

func sizeFlowEvent(m *FlowEvent) int {
	n := 0
	if len(m.EventId) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.EventId))
	}
	if m.Timestamp != nil {
		s := sizeTimestamp(m.Timestamp)
		n += protowire.SizeTag(2) + protowire.SizeBytes(s)
	}
	if len(m.PublicKey) > 0 {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.PublicKey))
	}
	if m.FlowFields != nil {
		s := sizeFlowFields(m.FlowFields)
		n += protowire.SizeTag(4) + protowire.SizeBytes(s)
	}
	if m.IsInitiator {
		n += protowire.SizeTag(5) + protowire.SizeVarint(protowire.EncodeBool(m.IsInitiator))
	}
	n += len(m.unknownFields)
	return n
}

func marshalFlowEvent(b []byte, m *FlowEvent) []byte {
	if len(m.EventId) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.EventId)
	}
	if m.Timestamp != nil {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(sizeTimestamp(m.Timestamp)))
		b = marshalTimestamp(b, m.Timestamp)
	}
	if len(m.PublicKey) > 0 {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, m.PublicKey)
	}
	if m.FlowFields != nil {
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(sizeFlowFields(m.FlowFields)))
		b = marshalFlowFields(b, m.FlowFields)
	}
	if m.IsInitiator {
		b = protowire.AppendTag(b, 5, protowire.VarintType)
		b = protowire.AppendVarint(b, protowire.EncodeBool(m.IsInitiator))
	}
	b = append(b, m.unknownFields...)
	return b
}

func unmarshalFlowEvent(m *FlowEvent, b []byte) error {
	*m = FlowEvent{}
	for len(b) > 0 {
		fieldStart := b
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.EventId = append(m.EventId[:0], v...)
			b = b[n:]
		case num == 2 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Timestamp = &timestamppb.Timestamp{}
			if err := unmarshalTimestamp(m.Timestamp, v); err != nil {
				return err
			}
			b = b[n:]
		case num == 3 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.PublicKey = append(m.PublicKey[:0], v...)
			b = b[n:]
		case num == 4 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			if m.FlowFields == nil {
				m.FlowFields = &FlowFields{}
			}
			if err := unmarshalFlowFields(m.FlowFields, v); err != nil {
				return err
			}
			b = b[n:]
		case num == 5 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.IsInitiator = protowire.DecodeBool(v)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, fieldStart[:n+skip]...)
			b = b[skip:]
		}
	}
	return nil
}

func mergeFlowEvent(dst, src *FlowEvent) {
	if len(src.EventId) > 0 {
		dst.EventId = append(dst.EventId[:0], src.EventId...)
	}
	if src.Timestamp != nil {
		if dst.Timestamp == nil {
			dst.Timestamp = &timestamppb.Timestamp{}
		}
		mergeTimestamp(dst.Timestamp, src.Timestamp)
	}
	if len(src.PublicKey) > 0 {
		dst.PublicKey = append(dst.PublicKey[:0], src.PublicKey...)
	}
	if src.FlowFields != nil {
		if dst.FlowFields == nil {
			dst.FlowFields = &FlowFields{}
		}
		mergeFlowFields(dst.FlowFields, src.FlowFields)
	}
	if src.IsInitiator {
		dst.IsInitiator = src.IsInitiator
	}
	if len(src.unknownFields) > 0 {
		dst.unknownFields = append(dst.unknownFields, src.unknownFields...)
	}
}

func equalFlowEvent(a, b *FlowEvent) bool {
	if !bytes.Equal(a.EventId, b.EventId) {
		return false
	}
	if !equalTimestamp(a.Timestamp, b.Timestamp) {
		return false
	}
	if !bytes.Equal(a.PublicKey, b.PublicKey) {
		return false
	}
	if (a.FlowFields == nil) != (b.FlowFields == nil) {
		return false
	}
	if a.FlowFields != nil && !equalFlowFields(a.FlowFields, b.FlowFields) {
		return false
	}
	if a.IsInitiator != b.IsInitiator {
		return false
	}
	if !bytes.Equal(a.unknownFields, b.unknownFields) {
		return false
	}
	return true
}

func sizeFlowEventAck(m *FlowEventAck) int {
	n := 0
	if len(m.EventId) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.EventId))
	}
	if m.IsInitiator {
		n += protowire.SizeTag(2) + protowire.SizeVarint(protowire.EncodeBool(m.IsInitiator))
	}
	n += len(m.unknownFields)
	return n
}

func marshalFlowEventAck(b []byte, m *FlowEventAck) []byte {
	if len(m.EventId) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.EventId)
	}
	if m.IsInitiator {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, protowire.EncodeBool(m.IsInitiator))
	}
	b = append(b, m.unknownFields...)
	return b
}

func unmarshalFlowEventAck(m *FlowEventAck, b []byte) error {
	*m = FlowEventAck{}
	for len(b) > 0 {
		fieldStart := b
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.EventId = append(m.EventId[:0], v...)
			b = b[n:]
		case num == 2 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.IsInitiator = protowire.DecodeBool(v)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, fieldStart[:n+skip]...)
			b = b[skip:]
		}
	}
	return nil
}

func mergeFlowEventAck(dst, src *FlowEventAck) {
	if len(src.EventId) > 0 {
		dst.EventId = append(dst.EventId[:0], src.EventId...)
	}
	if src.IsInitiator {
		dst.IsInitiator = src.IsInitiator
	}
	if len(src.unknownFields) > 0 {
		dst.unknownFields = append(dst.unknownFields, src.unknownFields...)
	}
}

func equalFlowEventAck(a, b *FlowEventAck) bool {
	if !bytes.Equal(a.EventId, b.EventId) {
		return false
	}
	if a.IsInitiator != b.IsInitiator {
		return false
	}
	if !bytes.Equal(a.unknownFields, b.unknownFields) {
		return false
	}
	return true
}

func sizeFlowFields(m *FlowFields) int {
	n := 0
	if len(m.FlowId) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.FlowId))
	}
	if m.Type != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.Type))
	}
	if len(m.RuleId) > 0 {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.RuleId))
	}
	if m.Direction != 0 {
		n += protowire.SizeTag(4) + protowire.SizeVarint(uint64(m.Direction))
	}
	if m.Protocol != 0 {
		n += protowire.SizeTag(5) + protowire.SizeVarint(uint64(m.Protocol))
	}
	if len(m.SourceIp) > 0 {
		n += protowire.SizeTag(6) + protowire.SizeBytes(len(m.SourceIp))
	}
	if len(m.DestIp) > 0 {
		n += protowire.SizeTag(7) + protowire.SizeBytes(len(m.DestIp))
	}
	if v, ok := m.ConnectionInfo.(*FlowFields_PortInfo); ok && v.PortInfo != nil {
		s := sizePortInfo(v.PortInfo)
		n += protowire.SizeTag(8) + protowire.SizeBytes(s)
	}
	if v, ok := m.ConnectionInfo.(*FlowFields_IcmpInfo); ok && v.IcmpInfo != nil {
		s := sizeICMPInfo(v.IcmpInfo)
		n += protowire.SizeTag(9) + protowire.SizeBytes(s)
	}
	if m.RxPackets != 0 {
		n += protowire.SizeTag(10) + protowire.SizeVarint(uint64(m.RxPackets))
	}
	if m.TxPackets != 0 {
		n += protowire.SizeTag(11) + protowire.SizeVarint(uint64(m.TxPackets))
	}
	if m.RxBytes != 0 {
		n += protowire.SizeTag(12) + protowire.SizeVarint(uint64(m.RxBytes))
	}
	if m.TxBytes != 0 {
		n += protowire.SizeTag(13) + protowire.SizeVarint(uint64(m.TxBytes))
	}
	if len(m.SourceResourceId) > 0 {
		n += protowire.SizeTag(14) + protowire.SizeBytes(len(m.SourceResourceId))
	}
	if len(m.DestResourceId) > 0 {
		n += protowire.SizeTag(15) + protowire.SizeBytes(len(m.DestResourceId))
	}
	n += len(m.unknownFields)
	return n
}

func marshalFlowFields(b []byte, m *FlowFields) []byte {
	if len(m.FlowId) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.FlowId)
	}
	if m.Type != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Type))
	}
	if len(m.RuleId) > 0 {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, m.RuleId)
	}
	if m.Direction != 0 {
		b = protowire.AppendTag(b, 4, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Direction))
	}
	if m.Protocol != 0 {
		b = protowire.AppendTag(b, 5, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Protocol))
	}
	if len(m.SourceIp) > 0 {
		b = protowire.AppendTag(b, 6, protowire.BytesType)
		b = protowire.AppendBytes(b, m.SourceIp)
	}
	if len(m.DestIp) > 0 {
		b = protowire.AppendTag(b, 7, protowire.BytesType)
		b = protowire.AppendBytes(b, m.DestIp)
	}
	if v, ok := m.ConnectionInfo.(*FlowFields_PortInfo); ok && v.PortInfo != nil {
		b = protowire.AppendTag(b, 8, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(sizePortInfo(v.PortInfo)))
		b = marshalPortInfo(b, v.PortInfo)
	}
	if v, ok := m.ConnectionInfo.(*FlowFields_IcmpInfo); ok && v.IcmpInfo != nil {
		b = protowire.AppendTag(b, 9, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(sizeICMPInfo(v.IcmpInfo)))
		b = marshalICMPInfo(b, v.IcmpInfo)
	}
	if m.RxPackets != 0 {
		b = protowire.AppendTag(b, 10, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.RxPackets))
	}
	if m.TxPackets != 0 {
		b = protowire.AppendTag(b, 11, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.TxPackets))
	}
	if m.RxBytes != 0 {
		b = protowire.AppendTag(b, 12, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.RxBytes))
	}
	if m.TxBytes != 0 {
		b = protowire.AppendTag(b, 13, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.TxBytes))
	}
	if len(m.SourceResourceId) > 0 {
		b = protowire.AppendTag(b, 14, protowire.BytesType)
		b = protowire.AppendBytes(b, m.SourceResourceId)
	}
	if len(m.DestResourceId) > 0 {
		b = protowire.AppendTag(b, 15, protowire.BytesType)
		b = protowire.AppendBytes(b, m.DestResourceId)
	}
	b = append(b, m.unknownFields...)
	return b
}

func unmarshalFlowFields(m *FlowFields, b []byte) error {
	*m = FlowFields{}
	for len(b) > 0 {
		fieldStart := b
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.FlowId = append(m.FlowId[:0], v...)
			b = b[n:]
		case num == 2 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Type = Type(v)
			b = b[n:]
		case num == 3 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RuleId = append(m.RuleId[:0], v...)
			b = b[n:]
		case num == 4 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Direction = Direction(v)
			b = b[n:]
		case num == 5 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Protocol = uint32(v)
			b = b[n:]
		case num == 6 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.SourceIp = append(m.SourceIp[:0], v...)
			b = b[n:]
		case num == 7 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.DestIp = append(m.DestIp[:0], v...)
			b = b[n:]
		case num == 8 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			item := &PortInfo{}
			if err := unmarshalPortInfo(item, v); err != nil {
				return err
			}
			m.ConnectionInfo = &FlowFields_PortInfo{PortInfo: item}
			b = b[n:]
		case num == 9 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			item := &ICMPInfo{}
			if err := unmarshalICMPInfo(item, v); err != nil {
				return err
			}
			m.ConnectionInfo = &FlowFields_IcmpInfo{IcmpInfo: item}
			b = b[n:]
		case num == 10 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RxPackets = uint64(v)
			b = b[n:]
		case num == 11 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.TxPackets = uint64(v)
			b = b[n:]
		case num == 12 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RxBytes = uint64(v)
			b = b[n:]
		case num == 13 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.TxBytes = uint64(v)
			b = b[n:]
		case num == 14 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.SourceResourceId = append(m.SourceResourceId[:0], v...)
			b = b[n:]
		case num == 15 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.DestResourceId = append(m.DestResourceId[:0], v...)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, fieldStart[:n+skip]...)
			b = b[skip:]
		}
	}
	return nil
}

func mergeFlowFields(dst, src *FlowFields) {
	if len(src.FlowId) > 0 {
		dst.FlowId = append(dst.FlowId[:0], src.FlowId...)
	}
	if src.Type != 0 {
		dst.Type = src.Type
	}
	if len(src.RuleId) > 0 {
		dst.RuleId = append(dst.RuleId[:0], src.RuleId...)
	}
	if src.Direction != 0 {
		dst.Direction = src.Direction
	}
	if src.Protocol != 0 {
		dst.Protocol = src.Protocol
	}
	if len(src.SourceIp) > 0 {
		dst.SourceIp = append(dst.SourceIp[:0], src.SourceIp...)
	}
	if len(src.DestIp) > 0 {
		dst.DestIp = append(dst.DestIp[:0], src.DestIp...)
	}
	switch v := src.ConnectionInfo.(type) {
	case *FlowFields_PortInfo:
		if v.PortInfo != nil {
			cp := &PortInfo{}
			mergePortInfo(cp, v.PortInfo)
			dst.ConnectionInfo = &FlowFields_PortInfo{PortInfo: cp}
		}
	case *FlowFields_IcmpInfo:
		if v.IcmpInfo != nil {
			cp := &ICMPInfo{}
			mergeICMPInfo(cp, v.IcmpInfo)
			dst.ConnectionInfo = &FlowFields_IcmpInfo{IcmpInfo: cp}
		}
	}
	if src.RxPackets != 0 {
		dst.RxPackets = src.RxPackets
	}
	if src.TxPackets != 0 {
		dst.TxPackets = src.TxPackets
	}
	if src.RxBytes != 0 {
		dst.RxBytes = src.RxBytes
	}
	if src.TxBytes != 0 {
		dst.TxBytes = src.TxBytes
	}
	if len(src.SourceResourceId) > 0 {
		dst.SourceResourceId = append(dst.SourceResourceId[:0], src.SourceResourceId...)
	}
	if len(src.DestResourceId) > 0 {
		dst.DestResourceId = append(dst.DestResourceId[:0], src.DestResourceId...)
	}
	if len(src.unknownFields) > 0 {
		dst.unknownFields = append(dst.unknownFields, src.unknownFields...)
	}
}

func equalFlowFields(a, b *FlowFields) bool {
	if !bytes.Equal(a.FlowId, b.FlowId) {
		return false
	}
	if a.Type != b.Type {
		return false
	}
	if !bytes.Equal(a.RuleId, b.RuleId) {
		return false
	}
	if a.Direction != b.Direction {
		return false
	}
	if a.Protocol != b.Protocol {
		return false
	}
	if !bytes.Equal(a.SourceIp, b.SourceIp) {
		return false
	}
	if !bytes.Equal(a.DestIp, b.DestIp) {
		return false
	}
	if !equalFlowFieldsConnectionInfo(a.ConnectionInfo, b.ConnectionInfo) {
		return false
	}
	if a.RxPackets != b.RxPackets {
		return false
	}
	if a.TxPackets != b.TxPackets {
		return false
	}
	if a.RxBytes != b.RxBytes {
		return false
	}
	if a.TxBytes != b.TxBytes {
		return false
	}
	if !bytes.Equal(a.SourceResourceId, b.SourceResourceId) {
		return false
	}
	if !bytes.Equal(a.DestResourceId, b.DestResourceId) {
		return false
	}
	if !bytes.Equal(a.unknownFields, b.unknownFields) {
		return false
	}
	return true
}

func sizePortInfo(m *PortInfo) int {
	n := 0
	if m.SourcePort != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(m.SourcePort))
	}
	if m.DestPort != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.DestPort))
	}
	n += len(m.unknownFields)
	return n
}

func marshalPortInfo(b []byte, m *PortInfo) []byte {
	if m.SourcePort != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.SourcePort))
	}
	if m.DestPort != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.DestPort))
	}
	b = append(b, m.unknownFields...)
	return b
}

func unmarshalPortInfo(m *PortInfo, b []byte) error {
	*m = PortInfo{}
	for len(b) > 0 {
		fieldStart := b
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.SourcePort = uint32(v)
			b = b[n:]
		case num == 2 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.DestPort = uint32(v)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, fieldStart[:n+skip]...)
			b = b[skip:]
		}
	}
	return nil
}

func mergePortInfo(dst, src *PortInfo) {
	if src.SourcePort != 0 {
		dst.SourcePort = src.SourcePort
	}
	if src.DestPort != 0 {
		dst.DestPort = src.DestPort
	}
	if len(src.unknownFields) > 0 {
		dst.unknownFields = append(dst.unknownFields, src.unknownFields...)
	}
}

func equalPortInfo(a, b *PortInfo) bool {
	if a.SourcePort != b.SourcePort {
		return false
	}
	if a.DestPort != b.DestPort {
		return false
	}
	if !bytes.Equal(a.unknownFields, b.unknownFields) {
		return false
	}
	return true
}

func sizeICMPInfo(m *ICMPInfo) int {
	n := 0
	if m.IcmpType != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(m.IcmpType))
	}
	if m.IcmpCode != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.IcmpCode))
	}
	n += len(m.unknownFields)
	return n
}

func marshalICMPInfo(b []byte, m *ICMPInfo) []byte {
	if m.IcmpType != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.IcmpType))
	}
	if m.IcmpCode != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.IcmpCode))
	}
	b = append(b, m.unknownFields...)
	return b
}

func unmarshalICMPInfo(m *ICMPInfo, b []byte) error {
	*m = ICMPInfo{}
	for len(b) > 0 {
		fieldStart := b
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.IcmpType = uint32(v)
			b = b[n:]
		case num == 2 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.IcmpCode = uint32(v)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, fieldStart[:n+skip]...)
			b = b[skip:]
		}
	}
	return nil
}

func mergeICMPInfo(dst, src *ICMPInfo) {
	if src.IcmpType != 0 {
		dst.IcmpType = src.IcmpType
	}
	if src.IcmpCode != 0 {
		dst.IcmpCode = src.IcmpCode
	}
	if len(src.unknownFields) > 0 {
		dst.unknownFields = append(dst.unknownFields, src.unknownFields...)
	}
}

func equalICMPInfo(a, b *ICMPInfo) bool {
	if a.IcmpType != b.IcmpType {
		return false
	}
	if a.IcmpCode != b.IcmpCode {
		return false
	}
	if !bytes.Equal(a.unknownFields, b.unknownFields) {
		return false
	}
	return true
}

func sizeTimestamp(m *timestamppb.Timestamp) int {
	n := 0
	if m.Seconds != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(m.Seconds))
	}
	if m.Nanos != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.Nanos))
	}
	return n
}

func marshalTimestamp(b []byte, m *timestamppb.Timestamp) []byte {
	if m.Seconds != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Seconds))
	}
	if m.Nanos != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Nanos))
	}
	return b
}

func unmarshalTimestamp(m *timestamppb.Timestamp, b []byte) error {
	*m = timestamppb.Timestamp{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Seconds = int64(v)
			b = b[n:]
		case num == 2 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Nanos = int32(v)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			b = b[skip:]
		}
	}
	return nil
}

func mergeTimestamp(dst, src *timestamppb.Timestamp) {
	if src.Seconds != 0 {
		dst.Seconds = src.Seconds
	}
	if src.Nanos != 0 {
		dst.Nanos = src.Nanos
	}
}

func equalTimestamp(a, b *timestamppb.Timestamp) bool {
	if (a == nil) != (b == nil) {
		return false
	}
	if a == nil {
		return true
	}
	return a.Seconds == b.Seconds && a.Nanos == b.Nanos
}

func equalFlowFieldsConnectionInfo(a, b isFlowFields_ConnectionInfo) bool {
	switch av := a.(type) {
	case nil:
		return b == nil
	case *FlowFields_PortInfo:
		bv, ok := b.(*FlowFields_PortInfo)
		return ok && equalPortInfo(av.PortInfo, bv.PortInfo)
	case *FlowFields_IcmpInfo:
		bv, ok := b.(*FlowFields_IcmpInfo)
		return ok && equalICMPInfo(av.IcmpInfo, bv.IcmpInfo)
	default:
		return false
	}
}
