// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target flow; DO NOT EDIT.

//go:build tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func flowEventProtoReflect(m *FlowEvent) protoreflect.Message {
	return flowEventReflect{m: m}
}

func flowEventAckProtoReflect(m *FlowEventAck) protoreflect.Message {
	return flowEventAckReflect{m: m}
}

func flowFieldsProtoReflect(m *FlowFields) protoreflect.Message {
	return flowFieldsReflect{m: m}
}

func portInfoProtoReflect(m *PortInfo) protoreflect.Message {
	return portInfoReflect{m: m}
}

func iCMPInfoProtoReflect(m *ICMPInfo) protoreflect.Message {
	return iCMPInfoReflect{m: m}
}
