// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target flow; DO NOT EDIT.

//go:build !tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func flowEventProtoReflect(*FlowEvent) protoreflect.Message { return nil }

func flowEventAckProtoReflect(*FlowEventAck) protoreflect.Message { return nil }

func flowFieldsProtoReflect(*FlowFields) protoreflect.Message { return nil }

func portInfoProtoReflect(*PortInfo) protoreflect.Message { return nil }

func iCMPInfoProtoReflect(*ICMPInfo) protoreflect.Message { return nil }
