// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target management; DO NOT EDIT.

//go:build tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func encryptedMessageProtoReflect(m *EncryptedMessage) protoreflect.Message {
	return encryptedMessageReflect{m: m}
}

func jobRequestProtoReflect(m *JobRequest) protoreflect.Message {
	return jobRequestReflect{m: m}
}

func jobResponseProtoReflect(m *JobResponse) protoreflect.Message {
	return jobResponseReflect{m: m}
}

func bundleParametersProtoReflect(m *BundleParameters) protoreflect.Message {
	return bundleParametersReflect{m: m}
}

func bundleResultProtoReflect(m *BundleResult) protoreflect.Message {
	return bundleResultReflect{m: m}
}

func syncRequestProtoReflect(m *SyncRequest) protoreflect.Message {
	return syncRequestReflect{m: m}
}

func syncMetaRequestProtoReflect(m *SyncMetaRequest) protoreflect.Message {
	return syncMetaRequestReflect{m: m}
}

func loginRequestProtoReflect(m *LoginRequest) protoreflect.Message {
	return loginRequestReflect{m: m}
}

func peerKeysProtoReflect(m *PeerKeys) protoreflect.Message {
	return peerKeysReflect{m: m}
}

func environmentProtoReflect(m *Environment) protoreflect.Message {
	return environmentReflect{m: m}
}

func fileProtoReflect(m *File) protoreflect.Message {
	return fileReflect{m: m}
}

func flagsProtoReflect(m *Flags) protoreflect.Message {
	return flagsReflect{m: m}
}

func peerSystemMetaProtoReflect(m *PeerSystemMeta) protoreflect.Message {
	return peerSystemMetaReflect{m: m}
}

func loginResponseProtoReflect(m *LoginResponse) protoreflect.Message {
	return loginResponseReflect{m: m}
}

func syncResponseProtoReflect(m *SyncResponse) protoreflect.Message {
	return syncResponseReflect{m: m}
}

func extendAuthSessionRequestProtoReflect(m *ExtendAuthSessionRequest) protoreflect.Message {
	return extendAuthSessionRequestReflect{m: m}
}

func extendAuthSessionResponseProtoReflect(m *ExtendAuthSessionResponse) protoreflect.Message {
	return extendAuthSessionResponseReflect{m: m}
}

func serverKeyResponseProtoReflect(m *ServerKeyResponse) protoreflect.Message {
	return serverKeyResponseReflect{m: m}
}

func emptyProtoReflect(m *Empty) protoreflect.Message {
	return emptyReflect{m: m}
}

func netbirdConfigProtoReflect(m *NetbirdConfig) protoreflect.Message {
	return netbirdConfigReflect{m: m}
}

func hostConfigProtoReflect(m *HostConfig) protoreflect.Message {
	return hostConfigReflect{m: m}
}

func relayConfigProtoReflect(m *RelayConfig) protoreflect.Message {
	return relayConfigReflect{m: m}
}

func flowConfigProtoReflect(m *FlowConfig) protoreflect.Message {
	return flowConfigReflect{m: m}
}

func jWTConfigProtoReflect(m *JWTConfig) protoreflect.Message {
	return jWTConfigReflect{m: m}
}

func protectedHostConfigProtoReflect(m *ProtectedHostConfig) protoreflect.Message {
	return protectedHostConfigReflect{m: m}
}

func peerConfigProtoReflect(m *PeerConfig) protoreflect.Message {
	return peerConfigReflect{m: m}
}

func autoUpdateSettingsProtoReflect(m *AutoUpdateSettings) protoreflect.Message {
	return autoUpdateSettingsReflect{m: m}
}

func networkMapProtoReflect(m *NetworkMap) protoreflect.Message {
	return networkMapReflect{m: m}
}

func sSHAuthProtoReflect(m *SSHAuth) protoreflect.Message {
	return sSHAuthReflect{m: m}
}

func machineUserIndexesProtoReflect(m *MachineUserIndexes) protoreflect.Message {
	return machineUserIndexesReflect{m: m}
}

func remotePeerConfigProtoReflect(m *RemotePeerConfig) protoreflect.Message {
	return remotePeerConfigReflect{m: m}
}

func routeProtoReflect(m *Route) protoreflect.Message {
	return routeReflect{m: m}
}

func dNSConfigProtoReflect(m *DNSConfig) protoreflect.Message {
	return dNSConfigReflect{m: m}
}

func customZoneProtoReflect(m *CustomZone) protoreflect.Message {
	return customZoneReflect{m: m}
}

func simpleRecordProtoReflect(m *SimpleRecord) protoreflect.Message {
	return simpleRecordReflect{m: m}
}

func nameServerGroupProtoReflect(m *NameServerGroup) protoreflect.Message {
	return nameServerGroupReflect{m: m}
}

func nameServerProtoReflect(m *NameServer) protoreflect.Message {
	return nameServerReflect{m: m}
}

func firewallRuleProtoReflect(m *FirewallRule) protoreflect.Message {
	return firewallRuleReflect{m: m}
}

func networkAddressProtoReflect(m *NetworkAddress) protoreflect.Message {
	return networkAddressReflect{m: m}
}

func sSHConfigProtoReflect(m *SSHConfig) protoreflect.Message {
	return sSHConfigReflect{m: m}
}

func checksProtoReflect(m *Checks) protoreflect.Message {
	return checksReflect{m: m}
}

func portInfoProtoReflect(m *PortInfo) protoreflect.Message {
	return portInfoReflect{m: m}
}

func portInfo_RangeProtoReflect(m *PortInfo_Range) protoreflect.Message {
	return portInfo_RangeReflect{m: m}
}

func routeFirewallRuleProtoReflect(m *RouteFirewallRule) protoreflect.Message {
	return routeFirewallRuleReflect{m: m}
}

func forwardingRuleProtoReflect(m *ForwardingRule) protoreflect.Message {
	return forwardingRuleReflect{m: m}
}

func deviceAuthorizationFlowRequestProtoReflect(m *DeviceAuthorizationFlowRequest) protoreflect.Message {
	return deviceAuthorizationFlowRequestReflect{m: m}
}

func deviceAuthorizationFlowProtoReflect(m *DeviceAuthorizationFlow) protoreflect.Message {
	return deviceAuthorizationFlowReflect{m: m}
}

func pKCEAuthorizationFlowRequestProtoReflect(m *PKCEAuthorizationFlowRequest) protoreflect.Message {
	return pKCEAuthorizationFlowRequestReflect{m: m}
}

func pKCEAuthorizationFlowProtoReflect(m *PKCEAuthorizationFlow) protoreflect.Message {
	return pKCEAuthorizationFlowReflect{m: m}
}

func providerConfigProtoReflect(m *ProviderConfig) protoreflect.Message {
	return providerConfigReflect{m: m}
}

func exposeServiceRequestProtoReflect(m *ExposeServiceRequest) protoreflect.Message {
	return exposeServiceRequestReflect{m: m}
}

func exposeServiceResponseProtoReflect(m *ExposeServiceResponse) protoreflect.Message {
	return exposeServiceResponseReflect{m: m}
}

func renewExposeRequestProtoReflect(m *RenewExposeRequest) protoreflect.Message {
	return renewExposeRequestReflect{m: m}
}

func renewExposeResponseProtoReflect(m *RenewExposeResponse) protoreflect.Message {
	return renewExposeResponseReflect{m: m}
}

func stopExposeRequestProtoReflect(m *StopExposeRequest) protoreflect.Message {
	return stopExposeRequestReflect{m: m}
}

func stopExposeResponseProtoReflect(m *StopExposeResponse) protoreflect.Message {
	return stopExposeResponseReflect{m: m}
}
