// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target management; DO NOT EDIT.

//go:build !tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func encryptedMessageProtoReflect(*EncryptedMessage) protoreflect.Message { return nil }

func jobRequestProtoReflect(*JobRequest) protoreflect.Message { return nil }

func jobResponseProtoReflect(*JobResponse) protoreflect.Message { return nil }

func bundleParametersProtoReflect(*BundleParameters) protoreflect.Message { return nil }

func bundleResultProtoReflect(*BundleResult) protoreflect.Message { return nil }

func syncRequestProtoReflect(*SyncRequest) protoreflect.Message { return nil }

func syncMetaRequestProtoReflect(*SyncMetaRequest) protoreflect.Message { return nil }

func loginRequestProtoReflect(*LoginRequest) protoreflect.Message { return nil }

func peerKeysProtoReflect(*PeerKeys) protoreflect.Message { return nil }

func environmentProtoReflect(*Environment) protoreflect.Message { return nil }

func fileProtoReflect(*File) protoreflect.Message { return nil }

func flagsProtoReflect(*Flags) protoreflect.Message { return nil }

func peerSystemMetaProtoReflect(*PeerSystemMeta) protoreflect.Message { return nil }

func loginResponseProtoReflect(*LoginResponse) protoreflect.Message { return nil }

func syncResponseProtoReflect(*SyncResponse) protoreflect.Message { return nil }

func extendAuthSessionRequestProtoReflect(*ExtendAuthSessionRequest) protoreflect.Message { return nil }

func extendAuthSessionResponseProtoReflect(*ExtendAuthSessionResponse) protoreflect.Message {
	return nil
}

func serverKeyResponseProtoReflect(*ServerKeyResponse) protoreflect.Message { return nil }

func emptyProtoReflect(*Empty) protoreflect.Message { return nil }

func netbirdConfigProtoReflect(*NetbirdConfig) protoreflect.Message { return nil }

func hostConfigProtoReflect(*HostConfig) protoreflect.Message { return nil }

func relayConfigProtoReflect(*RelayConfig) protoreflect.Message { return nil }

func flowConfigProtoReflect(*FlowConfig) protoreflect.Message { return nil }

func jWTConfigProtoReflect(*JWTConfig) protoreflect.Message { return nil }

func protectedHostConfigProtoReflect(*ProtectedHostConfig) protoreflect.Message { return nil }

func peerConfigProtoReflect(*PeerConfig) protoreflect.Message { return nil }

func autoUpdateSettingsProtoReflect(*AutoUpdateSettings) protoreflect.Message { return nil }

func networkMapProtoReflect(*NetworkMap) protoreflect.Message { return nil }

func sSHAuthProtoReflect(*SSHAuth) protoreflect.Message { return nil }

func machineUserIndexesProtoReflect(*MachineUserIndexes) protoreflect.Message { return nil }

func remotePeerConfigProtoReflect(*RemotePeerConfig) protoreflect.Message { return nil }

func routeProtoReflect(*Route) protoreflect.Message { return nil }

func dNSConfigProtoReflect(*DNSConfig) protoreflect.Message { return nil }

func customZoneProtoReflect(*CustomZone) protoreflect.Message { return nil }

func simpleRecordProtoReflect(*SimpleRecord) protoreflect.Message { return nil }

func nameServerGroupProtoReflect(*NameServerGroup) protoreflect.Message { return nil }

func nameServerProtoReflect(*NameServer) protoreflect.Message { return nil }

func firewallRuleProtoReflect(*FirewallRule) protoreflect.Message { return nil }

func networkAddressProtoReflect(*NetworkAddress) protoreflect.Message { return nil }

func sSHConfigProtoReflect(*SSHConfig) protoreflect.Message { return nil }

func checksProtoReflect(*Checks) protoreflect.Message { return nil }

func portInfoProtoReflect(*PortInfo) protoreflect.Message { return nil }

func portInfo_RangeProtoReflect(*PortInfo_Range) protoreflect.Message { return nil }

func routeFirewallRuleProtoReflect(*RouteFirewallRule) protoreflect.Message { return nil }

func forwardingRuleProtoReflect(*ForwardingRule) protoreflect.Message { return nil }

func deviceAuthorizationFlowRequestProtoReflect(*DeviceAuthorizationFlowRequest) protoreflect.Message {
	return nil
}

func deviceAuthorizationFlowProtoReflect(*DeviceAuthorizationFlow) protoreflect.Message { return nil }

func pKCEAuthorizationFlowRequestProtoReflect(*PKCEAuthorizationFlowRequest) protoreflect.Message {
	return nil
}

func pKCEAuthorizationFlowProtoReflect(*PKCEAuthorizationFlow) protoreflect.Message { return nil }

func providerConfigProtoReflect(*ProviderConfig) protoreflect.Message { return nil }

func exposeServiceRequestProtoReflect(*ExposeServiceRequest) protoreflect.Message { return nil }

func exposeServiceResponseProtoReflect(*ExposeServiceResponse) protoreflect.Message { return nil }

func renewExposeRequestProtoReflect(*RenewExposeRequest) protoreflect.Message { return nil }

func renewExposeResponseProtoReflect(*RenewExposeResponse) protoreflect.Message { return nil }

func stopExposeRequestProtoReflect(*StopExposeRequest) protoreflect.Message { return nil }

func stopExposeResponseProtoReflect(*StopExposeResponse) protoreflect.Message { return nil }
