// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target management; DO NOT EDIT.

//go:build tinygo

package proto

import (
	"bytes"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
)

type encryptedMessageReflect struct{ m *EncryptedMessage }

func protoCanary(method string) string {
	return "management proto fast-path: unexpected protoreflect.Message." + method
}

func (r encryptedMessageReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r encryptedMessageReflect) Type() protoreflect.MessageType { panic(protoCanary("Type")) }
func (r encryptedMessageReflect) New() protoreflect.Message {
	return encryptedMessageReflect{m: new(EncryptedMessage)}
}
func (r encryptedMessageReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r encryptedMessageReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r encryptedMessageReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r encryptedMessageReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r encryptedMessageReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r encryptedMessageReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r encryptedMessageReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r encryptedMessageReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r encryptedMessageReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r encryptedMessageReflect) GetUnknown() protoreflect.RawFields { return r.m.unknownFields }
func (r encryptedMessageReflect) SetUnknown(f protoreflect.RawFields) {
	r.m.unknownFields = append(r.m.unknownFields[:0], f...)
}
func (r encryptedMessageReflect) IsValid() bool                     { return r.m != nil }
func (r encryptedMessageReflect) ProtoMethods() *protoiface.Methods { return &encryptedMessageMethods }

var encryptedMessageMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeEncryptedMessage(in.Message.(encryptedMessageReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalEncryptedMessage(in.Buf, in.Message.(encryptedMessageReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalEncryptedMessage(in.Message.(encryptedMessageReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeEncryptedMessage(in.Destination.(encryptedMessageReflect).m, in.Source.(encryptedMessageReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalEncryptedMessage(in.MessageA.(encryptedMessageReflect).m, in.MessageB.(encryptedMessageReflect).m)}
	},
}

func sizeEncryptedMessage(m *EncryptedMessage) int {
	n := 0
	if m.WgPubKey != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.WgPubKey))
	}
	if len(m.Body) > 0 {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Body))
	}
	if m.Version != 0 {
		n += protowire.SizeTag(3) + protowire.SizeVarint(uint64(m.Version))
	}
	n += len(m.unknownFields)
	return n
}

func marshalEncryptedMessage(b []byte, m *EncryptedMessage) []byte {
	if m.WgPubKey != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.WgPubKey)
	}
	if len(m.Body) > 0 {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendBytes(b, m.Body)
	}
	if m.Version != 0 {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Version))
	}
	b = append(b, m.unknownFields...)
	return b
}

func unmarshalEncryptedMessage(m *EncryptedMessage, b []byte) error {
	*m = EncryptedMessage{}
	for len(b) > 0 {
		fieldStart := b
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.WgPubKey = v
			b = b[n:]
		case num == 2 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Body = append(m.Body[:0], v...)
			b = b[n:]
		case num == 3 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Version = int32(v)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, fieldStart[:n+skip]...)
			b = b[skip:]
		}
	}
	return nil
}

func mergeEncryptedMessage(dst, src *EncryptedMessage) {
	if src.WgPubKey != "" {
		dst.WgPubKey = src.WgPubKey
	}
	if len(src.Body) > 0 {
		dst.Body = append(dst.Body[:0], src.Body...)
	}
	if src.Version != 0 {
		dst.Version = src.Version
	}
	if len(src.unknownFields) > 0 {
		dst.unknownFields = append(dst.unknownFields, src.unknownFields...)
	}
}

func equalEncryptedMessage(a, b *EncryptedMessage) bool {
	if a.WgPubKey != b.WgPubKey {
		return false
	}
	if !bytes.Equal(a.Body, b.Body) {
		return false
	}
	if a.Version != b.Version {
		return false
	}
	if !bytes.Equal(a.unknownFields, b.unknownFields) {
		return false
	}
	return true
}
