// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target management; DO NOT EDIT.

//go:build !tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func encryptedMessageProtoReflect(*EncryptedMessage) protoreflect.Message { return nil }
