// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target proxy_service; DO NOT EDIT.

//go:build tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func proxyCapabilitiesProtoReflect(m *ProxyCapabilities) protoreflect.Message {
	return proxyCapabilitiesReflect{m: m}
}

func getMappingUpdateRequestProtoReflect(m *GetMappingUpdateRequest) protoreflect.Message {
	return getMappingUpdateRequestReflect{m: m}
}

func getMappingUpdateResponseProtoReflect(m *GetMappingUpdateResponse) protoreflect.Message {
	return getMappingUpdateResponseReflect{m: m}
}

func pathTargetOptionsProtoReflect(m *PathTargetOptions) protoreflect.Message {
	return pathTargetOptionsReflect{m: m}
}

func pathMappingProtoReflect(m *PathMapping) protoreflect.Message {
	return pathMappingReflect{m: m}
}

func headerAuthProtoReflect(m *HeaderAuth) protoreflect.Message {
	return headerAuthReflect{m: m}
}

func authenticationProtoReflect(m *Authentication) protoreflect.Message {
	return authenticationReflect{m: m}
}

func accessRestrictionsProtoReflect(m *AccessRestrictions) protoreflect.Message {
	return accessRestrictionsReflect{m: m}
}

func proxyMappingProtoReflect(m *ProxyMapping) protoreflect.Message {
	return proxyMappingReflect{m: m}
}

func sendAccessLogRequestProtoReflect(m *SendAccessLogRequest) protoreflect.Message {
	return sendAccessLogRequestReflect{m: m}
}

func sendAccessLogResponseProtoReflect(m *SendAccessLogResponse) protoreflect.Message {
	return sendAccessLogResponseReflect{m: m}
}

func accessLogProtoReflect(m *AccessLog) protoreflect.Message {
	return accessLogReflect{m: m}
}

func authenticateRequestProtoReflect(m *AuthenticateRequest) protoreflect.Message {
	return authenticateRequestReflect{m: m}
}

func headerAuthRequestProtoReflect(m *HeaderAuthRequest) protoreflect.Message {
	return headerAuthRequestReflect{m: m}
}

func passwordRequestProtoReflect(m *PasswordRequest) protoreflect.Message {
	return passwordRequestReflect{m: m}
}

func pinRequestProtoReflect(m *PinRequest) protoreflect.Message {
	return pinRequestReflect{m: m}
}

func authenticateResponseProtoReflect(m *AuthenticateResponse) protoreflect.Message {
	return authenticateResponseReflect{m: m}
}

func sendStatusUpdateRequestProtoReflect(m *SendStatusUpdateRequest) protoreflect.Message {
	return sendStatusUpdateRequestReflect{m: m}
}

func proxyInboundListenerProtoReflect(m *ProxyInboundListener) protoreflect.Message {
	return proxyInboundListenerReflect{m: m}
}

func sendStatusUpdateResponseProtoReflect(m *SendStatusUpdateResponse) protoreflect.Message {
	return sendStatusUpdateResponseReflect{m: m}
}

func createProxyPeerRequestProtoReflect(m *CreateProxyPeerRequest) protoreflect.Message {
	return createProxyPeerRequestReflect{m: m}
}

func createProxyPeerResponseProtoReflect(m *CreateProxyPeerResponse) protoreflect.Message {
	return createProxyPeerResponseReflect{m: m}
}

func getOIDCURLRequestProtoReflect(m *GetOIDCURLRequest) protoreflect.Message {
	return getOIDCURLRequestReflect{m: m}
}

func getOIDCURLResponseProtoReflect(m *GetOIDCURLResponse) protoreflect.Message {
	return getOIDCURLResponseReflect{m: m}
}

func validateSessionRequestProtoReflect(m *ValidateSessionRequest) protoreflect.Message {
	return validateSessionRequestReflect{m: m}
}

func validateSessionResponseProtoReflect(m *ValidateSessionResponse) protoreflect.Message {
	return validateSessionResponseReflect{m: m}
}

func validateTunnelPeerRequestProtoReflect(m *ValidateTunnelPeerRequest) protoreflect.Message {
	return validateTunnelPeerRequestReflect{m: m}
}

func validateTunnelPeerResponseProtoReflect(m *ValidateTunnelPeerResponse) protoreflect.Message {
	return validateTunnelPeerResponseReflect{m: m}
}

func syncMappingsRequestProtoReflect(m *SyncMappingsRequest) protoreflect.Message {
	return syncMappingsRequestReflect{m: m}
}

func syncMappingsInitProtoReflect(m *SyncMappingsInit) protoreflect.Message {
	return syncMappingsInitReflect{m: m}
}

func syncMappingsAckProtoReflect(m *SyncMappingsAck) protoreflect.Message {
	return syncMappingsAckReflect{m: m}
}

func syncMappingsResponseProtoReflect(m *SyncMappingsResponse) protoreflect.Message {
	return syncMappingsResponseReflect{m: m}
}
