// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target proxy_service; DO NOT EDIT.

//go:build !tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func proxyCapabilitiesProtoReflect(*ProxyCapabilities) protoreflect.Message { return nil }

func getMappingUpdateRequestProtoReflect(*GetMappingUpdateRequest) protoreflect.Message { return nil }

func getMappingUpdateResponseProtoReflect(*GetMappingUpdateResponse) protoreflect.Message { return nil }

func pathTargetOptionsProtoReflect(*PathTargetOptions) protoreflect.Message { return nil }

func pathMappingProtoReflect(*PathMapping) protoreflect.Message { return nil }

func headerAuthProtoReflect(*HeaderAuth) protoreflect.Message { return nil }

func authenticationProtoReflect(*Authentication) protoreflect.Message { return nil }

func accessRestrictionsProtoReflect(*AccessRestrictions) protoreflect.Message { return nil }

func proxyMappingProtoReflect(*ProxyMapping) protoreflect.Message { return nil }

func sendAccessLogRequestProtoReflect(*SendAccessLogRequest) protoreflect.Message { return nil }

func sendAccessLogResponseProtoReflect(*SendAccessLogResponse) protoreflect.Message { return nil }

func accessLogProtoReflect(*AccessLog) protoreflect.Message { return nil }

func authenticateRequestProtoReflect(*AuthenticateRequest) protoreflect.Message { return nil }

func headerAuthRequestProtoReflect(*HeaderAuthRequest) protoreflect.Message { return nil }

func passwordRequestProtoReflect(*PasswordRequest) protoreflect.Message { return nil }

func pinRequestProtoReflect(*PinRequest) protoreflect.Message { return nil }

func authenticateResponseProtoReflect(*AuthenticateResponse) protoreflect.Message { return nil }

func sendStatusUpdateRequestProtoReflect(*SendStatusUpdateRequest) protoreflect.Message { return nil }

func proxyInboundListenerProtoReflect(*ProxyInboundListener) protoreflect.Message { return nil }

func sendStatusUpdateResponseProtoReflect(*SendStatusUpdateResponse) protoreflect.Message { return nil }

func createProxyPeerRequestProtoReflect(*CreateProxyPeerRequest) protoreflect.Message { return nil }

func createProxyPeerResponseProtoReflect(*CreateProxyPeerResponse) protoreflect.Message { return nil }

func getOIDCURLRequestProtoReflect(*GetOIDCURLRequest) protoreflect.Message { return nil }

func getOIDCURLResponseProtoReflect(*GetOIDCURLResponse) protoreflect.Message { return nil }

func validateSessionRequestProtoReflect(*ValidateSessionRequest) protoreflect.Message { return nil }

func validateSessionResponseProtoReflect(*ValidateSessionResponse) protoreflect.Message { return nil }

func validateTunnelPeerRequestProtoReflect(*ValidateTunnelPeerRequest) protoreflect.Message {
	return nil
}

func validateTunnelPeerResponseProtoReflect(*ValidateTunnelPeerResponse) protoreflect.Message {
	return nil
}

func syncMappingsRequestProtoReflect(*SyncMappingsRequest) protoreflect.Message { return nil }

func syncMappingsInitProtoReflect(*SyncMappingsInit) protoreflect.Message { return nil }

func syncMappingsAckProtoReflect(*SyncMappingsAck) protoreflect.Message { return nil }

func syncMappingsResponseProtoReflect(*SyncMappingsResponse) protoreflect.Message { return nil }
