//go:build tinygo

// Code generated by embedpb. DO NOT EDIT.
// Reflection-free, TinyGo-safe proto codec: hand-written protoiface.Methods
// keep google.golang.org/protobuf on its fast path (no reflect coder).
package proto

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"math"
	"sort"
	"strconv"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
)

var _ = math.Float32bits
var _ = sort.Strings
var _ = fmt.Sprintf
var _ = bytes.Equal
var _ = strconv.AppendInt
var _ = base64.StdEncoding

type Body_Type int32

const (
	Body_OFFER     Body_Type = 0
	Body_ANSWER    Body_Type = 1
	Body_CANDIDATE Body_Type = 2
	Body_MODE      Body_Type = 4
	Body_GO_IDLE   Body_Type = 5
	Body_HEARTBEAT Body_Type = 6
)

var Body_Type_name = map[int32]string{
	0: "OFFER",
	1: "ANSWER",
	2: "CANDIDATE",
	4: "MODE",
	5: "GO_IDLE",
	6: "HEARTBEAT",
}

func (x Body_Type) String() string {
	if s, ok := Body_Type_name[int32(x)]; ok {
		return s
	}
	return fmt.Sprintf("Body_Type(%d)", int32(x))
}
func (x Body_Type) Enum() *Body_Type { p := new(Body_Type); *p = x; return p }

type Body struct {
	Type               Body_Type
	Payload            string
	WgListenPort       uint32
	NetBirdVersion     string
	Mode               *Mode
	FeaturesSupported  []uint32
	RosenpassConfig    *RosenpassConfig
	RelayServerAddress *string
	SessionId          []byte
	RelayServerIP      []byte
	unknownFields      protoreflect.RawFields
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return fmt.Sprintf("Body{}") }
func (m *Body) ProtoMessage()  {}
func (m *Body) GetType() Body_Type {
	if m != nil {
		return m.Type
	}
	return Body_Type(0)
}
func (m *Body) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}
func (m *Body) GetWgListenPort() uint32 {
	if m != nil {
		return m.WgListenPort
	}
	return 0
}
func (m *Body) GetNetBirdVersion() string {
	if m != nil {
		return m.NetBirdVersion
	}
	return ""
}
func (m *Body) GetMode() *Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}
func (m *Body) GetFeaturesSupported() []uint32 {
	if m != nil {
		return m.FeaturesSupported
	}
	return nil
}
func (m *Body) GetRosenpassConfig() *RosenpassConfig {
	if m != nil {
		return m.RosenpassConfig
	}
	return nil
}
func (m *Body) GetRelayServerAddress() string {
	if m != nil && m.RelayServerAddress != nil {
		return *m.RelayServerAddress
	}
	return ""
}
func (m *Body) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}
func (m *Body) GetRelayServerIP() []byte {
	if m != nil {
		return m.RelayServerIP
	}
	return nil
}

func (m *Body) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&Body{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *Body) sizeField() int {
	n := 0
	if m.Type != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(int64(m.Type)))
	}
	if m.Payload != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Payload))
	}
	if m.WgListenPort != 0 {
		n += protowire.SizeTag(3) + protowire.SizeVarint(uint64(m.WgListenPort))
	}
	if m.NetBirdVersion != "" {
		n += protowire.SizeTag(4) + protowire.SizeBytes(len(m.NetBirdVersion))
	}
	if m.Mode != nil {
		n += protowire.SizeTag(5) + protowire.SizeBytes(m.Mode.sizeField())
	}
	if len(m.FeaturesSupported) > 0 {
		pn := 0
		for _, v := range m.FeaturesSupported {
			pn += protowire.SizeVarint(uint64(v))
		}
		n += protowire.SizeTag(6) + protowire.SizeBytes(pn)
	}
	if m.RosenpassConfig != nil {
		n += protowire.SizeTag(7) + protowire.SizeBytes(m.RosenpassConfig.sizeField())
	}
	if m.RelayServerAddress != nil {
		n += protowire.SizeTag(8) + protowire.SizeBytes(len(*m.RelayServerAddress))
	}
	if m.SessionId != nil {
		n += protowire.SizeTag(10) + protowire.SizeBytes(len(m.SessionId))
	}
	if m.RelayServerIP != nil {
		n += protowire.SizeTag(11) + protowire.SizeBytes(len(m.RelayServerIP))
	}
	n += len(m.unknownFields)
	return n
}

func (m *Body) marshalAppend(b []byte) ([]byte, error) {
	if m.Type != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.Type)))
	}
	if m.Payload != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Payload)
	}
	if m.WgListenPort != 0 {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.WgListenPort))
	}
	if m.NetBirdVersion != "" {
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendString(b, m.NetBirdVersion)
	}
	if m.Mode != nil {
		sub, _ := m.Mode.marshalAppend(nil)
		b = protowire.AppendTag(b, 5, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if len(m.FeaturesSupported) > 0 {
		var packed []byte
		for _, v := range m.FeaturesSupported {
			packed = protowire.AppendVarint(packed, uint64(v))
		}
		b = protowire.AppendTag(b, 6, protowire.BytesType)
		b = protowire.AppendBytes(b, packed)
	}
	if m.RosenpassConfig != nil {
		sub, _ := m.RosenpassConfig.marshalAppend(nil)
		b = protowire.AppendTag(b, 7, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.RelayServerAddress != nil {
		b = protowire.AppendTag(b, 8, protowire.BytesType)
		b = protowire.AppendString(b, *m.RelayServerAddress)
	}
	if m.SessionId != nil {
		b = protowire.AppendTag(b, 10, protowire.BytesType)
		b = protowire.AppendBytes(b, m.SessionId)
	}
	if m.RelayServerIP != nil {
		b = protowire.AppendTag(b, 11, protowire.BytesType)
		b = protowire.AppendBytes(b, m.RelayServerIP)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *Body) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Type = Body_Type(v)
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Payload = v
		case 3:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.WgListenPort = uint32(v)
		case 4:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.NetBirdVersion = v
		case 5:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &Mode{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.Mode = mm
			}
		case 6:
			if typ == protowire.BytesType {
				pk, k := protowire.ConsumeBytes(b)
				consumed = k
				for len(pk) > 0 {
					v, kk := protowire.ConsumeVarint(pk)
					if kk < 0 {
						return protowire.ParseError(kk)
					}
					m.FeaturesSupported = append(m.FeaturesSupported, uint32(v))
					pk = pk[kk:]
				}
			} else {
				v, k := protowire.ConsumeVarint(b)
				consumed = k
				m.FeaturesSupported = append(m.FeaturesSupported, uint32(v))
			}
		case 7:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &RosenpassConfig{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.RosenpassConfig = mm
			}
		case 8:
			v, k := protowire.ConsumeString(b)
			consumed = k
			tmp := v
			m.RelayServerAddress = &tmp
		case 10:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.SessionId = append([]byte(nil), v...)
		case 11:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.RelayServerIP = append([]byte(nil), v...)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *Body) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *Body) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"type\":"...)
	if s, ok := Body_Type_name[int32(m.Type)]; ok {
		dst = jsonString(dst, s)
	} else {
		dst = strconv.AppendInt(dst, int64(m.Type), 10)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"payload\":"...)
	dst = jsonString(dst, m.Payload)
	dst = append(dst, ',')
	dst = append(dst, "\"wgListenPort\":"...)
	dst = strconv.AppendUint(dst, uint64(m.WgListenPort), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"netBirdVersion\":"...)
	dst = jsonString(dst, m.NetBirdVersion)
	dst = append(dst, ',')
	dst = append(dst, "\"mode\":"...)
	if m.Mode != nil {
		dst, err = m.Mode.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"featuresSupported\":"...)
	dst = append(dst, '[')
	for i, v := range m.FeaturesSupported {
		if i > 0 {
			dst = append(dst, ',')
		}
		dst = strconv.AppendUint(dst, uint64(v), 10)
	}
	dst = append(dst, ']')
	dst = append(dst, ',')
	dst = append(dst, "\"rosenpassConfig\":"...)
	if m.RosenpassConfig != nil {
		dst, err = m.RosenpassConfig.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"relayServerAddress\":"...)
	if m.RelayServerAddress != nil {
		dst = jsonString(dst, *m.RelayServerAddress)
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"sessionId\":"...)
	if m.SessionId != nil {
		dst = jsonBytes(dst, m.SessionId)
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"relayServerIP\":"...)
	if m.RelayServerIP != nil {
		dst = jsonBytes(dst, m.RelayServerIP)
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type EncryptedMessage struct {
	Key           string
	RemoteKey     string
	Body          []byte
	unknownFields protoreflect.RawFields
}

func (m *EncryptedMessage) Reset()         { *m = EncryptedMessage{} }
func (m *EncryptedMessage) String() string { return fmt.Sprintf("EncryptedMessage{}") }
func (m *EncryptedMessage) ProtoMessage()  {}
func (m *EncryptedMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}
func (m *EncryptedMessage) GetRemoteKey() string {
	if m != nil {
		return m.RemoteKey
	}
	return ""
}
func (m *EncryptedMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *EncryptedMessage) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&EncryptedMessage{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *EncryptedMessage) sizeField() int {
	n := 0
	if m.Key != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Key))
	}
	if m.RemoteKey != "" {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.RemoteKey))
	}
	if len(m.Body) > 0 {
		n += protowire.SizeTag(4) + protowire.SizeBytes(len(m.Body))
	}
	n += len(m.unknownFields)
	return n
}

func (m *EncryptedMessage) marshalAppend(b []byte) ([]byte, error) {
	if m.Key != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Key)
	}
	if m.RemoteKey != "" {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendString(b, m.RemoteKey)
	}
	if len(m.Body) > 0 {
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendBytes(b, m.Body)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *EncryptedMessage) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Key = v
		case 3:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.RemoteKey = v
		case 4:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.Body = append([]byte(nil), v...)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *EncryptedMessage) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *EncryptedMessage) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"key\":"...)
	dst = jsonString(dst, m.Key)
	dst = append(dst, ',')
	dst = append(dst, "\"remoteKey\":"...)
	dst = jsonString(dst, m.RemoteKey)
	dst = append(dst, ',')
	dst = append(dst, "\"body\":"...)
	dst = jsonBytes(dst, m.Body)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type Message struct {
	Key           string
	RemoteKey     string
	Body          *Body
	unknownFields protoreflect.RawFields
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return fmt.Sprintf("Message{}") }
func (m *Message) ProtoMessage()  {}
func (m *Message) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}
func (m *Message) GetRemoteKey() string {
	if m != nil {
		return m.RemoteKey
	}
	return ""
}
func (m *Message) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&Message{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *Message) sizeField() int {
	n := 0
	if m.Key != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Key))
	}
	if m.RemoteKey != "" {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.RemoteKey))
	}
	if m.Body != nil {
		n += protowire.SizeTag(4) + protowire.SizeBytes(m.Body.sizeField())
	}
	n += len(m.unknownFields)
	return n
}

func (m *Message) marshalAppend(b []byte) ([]byte, error) {
	if m.Key != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Key)
	}
	if m.RemoteKey != "" {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendString(b, m.RemoteKey)
	}
	if m.Body != nil {
		sub, _ := m.Body.marshalAppend(nil)
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *Message) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Key = v
		case 3:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.RemoteKey = v
		case 4:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &Body{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.Body = mm
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *Message) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *Message) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"key\":"...)
	dst = jsonString(dst, m.Key)
	dst = append(dst, ',')
	dst = append(dst, "\"remoteKey\":"...)
	dst = jsonString(dst, m.RemoteKey)
	dst = append(dst, ',')
	dst = append(dst, "\"body\":"...)
	if m.Body != nil {
		dst, err = m.Body.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type Mode struct {
	Direct        *bool
	unknownFields protoreflect.RawFields
}

func (m *Mode) Reset()         { *m = Mode{} }
func (m *Mode) String() string { return fmt.Sprintf("Mode{}") }
func (m *Mode) ProtoMessage()  {}
func (m *Mode) GetDirect() bool {
	if m != nil && m.Direct != nil {
		return *m.Direct
	}
	return false
}

func (m *Mode) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&Mode{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *Mode) sizeField() int {
	n := 0
	if m.Direct != nil {
		n += protowire.SizeTag(1) + protowire.SizeVarint(embedBool(*m.Direct))
	}
	n += len(m.unknownFields)
	return n
}

func (m *Mode) marshalAppend(b []byte) ([]byte, error) {
	if m.Direct != nil {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(*m.Direct))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *Mode) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			tmp := v != 0
			m.Direct = &tmp
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *Mode) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *Mode) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"direct\":"...)
	if m.Direct != nil {
		dst = strconv.AppendBool(dst, *m.Direct)
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type RosenpassConfig struct {
	RosenpassPubKey     []byte
	RosenpassServerAddr string
	unknownFields       protoreflect.RawFields
}

func (m *RosenpassConfig) Reset()         { *m = RosenpassConfig{} }
func (m *RosenpassConfig) String() string { return fmt.Sprintf("RosenpassConfig{}") }
func (m *RosenpassConfig) ProtoMessage()  {}
func (m *RosenpassConfig) GetRosenpassPubKey() []byte {
	if m != nil {
		return m.RosenpassPubKey
	}
	return nil
}
func (m *RosenpassConfig) GetRosenpassServerAddr() string {
	if m != nil {
		return m.RosenpassServerAddr
	}
	return ""
}

func (m *RosenpassConfig) ProtoReflect() protoreflect.Message {
	return msgReflect{marshal: m.marshalAppend, size: m.sizeField, unmarshal: m.unmarshalMsg, iface: m, valid: m != nil,
		newFn:      func() protoreflect.Message { return (&RosenpassConfig{}).ProtoReflect() },
		getUnknown: func() protoreflect.RawFields { return m.unknownFields },
		setUnknown: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *RosenpassConfig) sizeField() int {
	n := 0
	if len(m.RosenpassPubKey) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.RosenpassPubKey))
	}
	if m.RosenpassServerAddr != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.RosenpassServerAddr))
	}
	n += len(m.unknownFields)
	return n
}

func (m *RosenpassConfig) marshalAppend(b []byte) ([]byte, error) {
	if len(m.RosenpassPubKey) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.RosenpassPubKey)
	}
	if m.RosenpassServerAddr != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.RosenpassServerAddr)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *RosenpassConfig) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.RosenpassPubKey = append([]byte(nil), v...)
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.RosenpassServerAddr = v
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *RosenpassConfig) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *RosenpassConfig) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"rosenpassPubKey\":"...)
	dst = jsonBytes(dst, m.RosenpassPubKey)
	dst = append(dst, ',')
	dst = append(dst, "\"rosenpassServerAddr\":"...)
	dst = jsonString(dst, m.RosenpassServerAddr)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

func embedBool(v bool) uint64 {
	if v {
		return 1
	}
	return 0
}

type msgReflect struct {
	marshal    func([]byte) ([]byte, error)
	size       func() int
	unmarshal  func([]byte) error
	iface      protoreflect.ProtoMessage
	valid      bool
	newFn      func() protoreflect.Message
	getUnknown func() protoreflect.RawFields
	setUnknown func(protoreflect.RawFields)
}

var _ protoreflect.Message = msgReflect{}

func (r msgReflect) ProtoMethods() *protoiface.Methods    { return &embedMethods }
func (r msgReflect) Interface() protoreflect.ProtoMessage { return r.iface }
func (r msgReflect) IsValid() bool                        { return r.valid }
func (r msgReflect) New() protoreflect.Message            { return r.newFn() }
func (r msgReflect) GetUnknown() protoreflect.RawFields   { return r.getUnknown() }
func (r msgReflect) SetUnknown(f protoreflect.RawFields)  { r.setUnknown(f) }

func embedCanary(m string) string {
	return "CANARY: protoreflect.Message." + m + " called on reflection-free message"
}

func (r msgReflect) Descriptor() protoreflect.MessageDescriptor { panic(embedCanary("Descriptor")) }
func (r msgReflect) Type() protoreflect.MessageType             { panic(embedCanary("Type")) }
func (r msgReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(embedCanary("Range"))
}
func (r msgReflect) Has(protoreflect.FieldDescriptor) bool               { panic(embedCanary("Has")) }
func (r msgReflect) Clear(protoreflect.FieldDescriptor)                  { panic(embedCanary("Clear")) }
func (r msgReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value { panic(embedCanary("Get")) }
func (r msgReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(embedCanary("Set"))
}
func (r msgReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(embedCanary("Mutable"))
}
func (r msgReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(embedCanary("NewField"))
}
func (r msgReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(embedCanary("WhichOneof"))
}

var embedMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: in.Message.(msgReflect).size()}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		b, err := in.Message.(msgReflect).marshal(in.Buf)
		return protoiface.MarshalOutput{Buf: b}, err
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := in.Message.(msgReflect).unmarshal(in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		src := in.Source.(msgReflect)
		dst := in.Destination.(msgReflect)
		sb, _ := src.marshal(nil)
		if err := dst.unmarshal(sb); err != nil {
			return protoiface.MergeOutput{}
		}
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(in protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		a, ok1 := in.MessageA.(msgReflect)
		b, ok2 := in.MessageB.(msgReflect)
		if !ok1 || !ok2 {
			return protoiface.EqualOutput{Equal: false}
		}
		ab, _ := a.marshal(nil)
		bb, _ := b.marshal(nil)
		return protoiface.EqualOutput{Equal: bytes.Equal(ab, bb)}
	},
}

// --- protojson-compatible JSON helpers ---

func jsonEndObj(dst []byte) []byte {
	if n := len(dst); n > 0 && dst[n-1] == ',' {
		dst[n-1] = '}'
		return dst
	}
	return append(dst, '}')
}

func jsonHexDigit(b byte) byte {
	if b < 10 {
		return '0' + b
	}
	return 'a' + b - 10
}

func jsonString(dst []byte, s string) []byte {
	dst = append(dst, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '"':
			dst = append(dst, '\\', '"')
		case '\\':
			dst = append(dst, '\\', '\\')
		case '\n':
			dst = append(dst, '\\', 'n')
		case '\r':
			dst = append(dst, '\\', 'r')
		case '\t':
			dst = append(dst, '\\', 't')
		default:
			if c < 0x20 {
				dst = append(dst, '\\', 'u', '0', '0', jsonHexDigit(c>>4), jsonHexDigit(c&0xf))
			} else {
				dst = append(dst, c)
			}
		}
	}
	return append(dst, '"')
}

func jsonBytes(dst []byte, b []byte) []byte {
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, b)
	return append(dst, '"')
}

// jsonNanoFrac formats sub-second nanos as protojson does: trailing zero groups
// of three trimmed, leaving 3, 6, or 9 fractional digits.
func jsonNanoFrac(nanos int32) string {
	buf := fmt.Sprintf("%09d", nanos)
	n := 9
	for n > 3 && buf[n-1] == '0' && buf[n-2] == '0' && buf[n-3] == '0' {
		n -= 3
	}
	return buf[:n]
}
