// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target signal; DO NOT EDIT.

//go:build !tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func encryptedMessageProtoReflect(*EncryptedMessage) protoreflect.Message { return nil }

func messageProtoReflect(*Message) protoreflect.Message { return nil }

func bodyProtoReflect(*Body) protoreflect.Message { return nil }

func modeProtoReflect(*Mode) protoreflect.Message { return nil }

func rosenpassConfigProtoReflect(*RosenpassConfig) protoreflect.Message { return nil }
