// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target signal; DO NOT EDIT.

//go:build tinygo

package proto

import (
	"bytes"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
)

type encryptedMessageReflect struct{ m *EncryptedMessage }
type messageReflect struct{ m *Message }
type bodyReflect struct{ m *Body }
type modeReflect struct{ m *Mode }
type rosenpassConfigReflect struct{ m *RosenpassConfig }

func protoCanary(method string) string {
	return "signal proto fast-path: unexpected protoreflect.Message." + method
}

func (r encryptedMessageReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r encryptedMessageReflect) Type() protoreflect.MessageType { panic(protoCanary("Type")) }
func (r encryptedMessageReflect) New() protoreflect.Message {
	return encryptedMessageReflect{m: new(EncryptedMessage)}
}
func (r encryptedMessageReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r encryptedMessageReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r encryptedMessageReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r encryptedMessageReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r encryptedMessageReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r encryptedMessageReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r encryptedMessageReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r encryptedMessageReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r encryptedMessageReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r encryptedMessageReflect) GetUnknown() protoreflect.RawFields { return nil }
func (r encryptedMessageReflect) SetUnknown(protoreflect.RawFields)  {}
func (r encryptedMessageReflect) IsValid() bool                      { return r.m != nil }
func (r encryptedMessageReflect) ProtoMethods() *protoiface.Methods  { return &encryptedMessageMethods }

func (r messageReflect) Descriptor() protoreflect.MessageDescriptor { panic(protoCanary("Descriptor")) }
func (r messageReflect) Type() protoreflect.MessageType             { panic(protoCanary("Type")) }
func (r messageReflect) New() protoreflect.Message                  { return messageReflect{m: new(Message)} }
func (r messageReflect) Interface() protoreflect.ProtoMessage       { return r.m }
func (r messageReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r messageReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r messageReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r messageReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r messageReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r messageReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r messageReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r messageReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r messageReflect) GetUnknown() protoreflect.RawFields { return nil }
func (r messageReflect) SetUnknown(protoreflect.RawFields)  {}
func (r messageReflect) IsValid() bool                      { return r.m != nil }
func (r messageReflect) ProtoMethods() *protoiface.Methods  { return &messageMethods }

func (r bodyReflect) Descriptor() protoreflect.MessageDescriptor { panic(protoCanary("Descriptor")) }
func (r bodyReflect) Type() protoreflect.MessageType             { panic(protoCanary("Type")) }
func (r bodyReflect) New() protoreflect.Message                  { return bodyReflect{m: new(Body)} }
func (r bodyReflect) Interface() protoreflect.ProtoMessage       { return r.m }
func (r bodyReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r bodyReflect) Has(protoreflect.FieldDescriptor) bool                { panic(protoCanary("Has")) }
func (r bodyReflect) Clear(protoreflect.FieldDescriptor)                   { panic(protoCanary("Clear")) }
func (r bodyReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value  { panic(protoCanary("Get")) }
func (r bodyReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) { panic(protoCanary("Set")) }
func (r bodyReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r bodyReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r bodyReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r bodyReflect) GetUnknown() protoreflect.RawFields { return nil }
func (r bodyReflect) SetUnknown(protoreflect.RawFields)  {}
func (r bodyReflect) IsValid() bool                      { return r.m != nil }
func (r bodyReflect) ProtoMethods() *protoiface.Methods  { return &bodyMethods }

func (r modeReflect) Descriptor() protoreflect.MessageDescriptor { panic(protoCanary("Descriptor")) }
func (r modeReflect) Type() protoreflect.MessageType             { panic(protoCanary("Type")) }
func (r modeReflect) New() protoreflect.Message                  { return modeReflect{m: new(Mode)} }
func (r modeReflect) Interface() protoreflect.ProtoMessage       { return r.m }
func (r modeReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r modeReflect) Has(protoreflect.FieldDescriptor) bool                { panic(protoCanary("Has")) }
func (r modeReflect) Clear(protoreflect.FieldDescriptor)                   { panic(protoCanary("Clear")) }
func (r modeReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value  { panic(protoCanary("Get")) }
func (r modeReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) { panic(protoCanary("Set")) }
func (r modeReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r modeReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r modeReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r modeReflect) GetUnknown() protoreflect.RawFields { return nil }
func (r modeReflect) SetUnknown(protoreflect.RawFields)  {}
func (r modeReflect) IsValid() bool                      { return r.m != nil }
func (r modeReflect) ProtoMethods() *protoiface.Methods  { return &modeMethods }

func (r rosenpassConfigReflect) Descriptor() protoreflect.MessageDescriptor {
	panic(protoCanary("Descriptor"))
}
func (r rosenpassConfigReflect) Type() protoreflect.MessageType { panic(protoCanary("Type")) }
func (r rosenpassConfigReflect) New() protoreflect.Message {
	return rosenpassConfigReflect{m: new(RosenpassConfig)}
}
func (r rosenpassConfigReflect) Interface() protoreflect.ProtoMessage { return r.m }
func (r rosenpassConfigReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(protoCanary("Range"))
}
func (r rosenpassConfigReflect) Has(protoreflect.FieldDescriptor) bool { panic(protoCanary("Has")) }
func (r rosenpassConfigReflect) Clear(protoreflect.FieldDescriptor)    { panic(protoCanary("Clear")) }
func (r rosenpassConfigReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Get"))
}
func (r rosenpassConfigReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(protoCanary("Set"))
}
func (r rosenpassConfigReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("Mutable"))
}
func (r rosenpassConfigReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(protoCanary("NewField"))
}
func (r rosenpassConfigReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(protoCanary("WhichOneof"))
}
func (r rosenpassConfigReflect) GetUnknown() protoreflect.RawFields { return nil }
func (r rosenpassConfigReflect) SetUnknown(protoreflect.RawFields)  {}
func (r rosenpassConfigReflect) IsValid() bool                      { return r.m != nil }
func (r rosenpassConfigReflect) ProtoMethods() *protoiface.Methods  { return &rosenpassConfigMethods }

var encryptedMessageMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeEncryptedMessage(in.Message.(encryptedMessageReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalEncryptedMessage(in.Buf, in.Message.(encryptedMessageReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalEncryptedMessage(in.Message.(encryptedMessageReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeEncryptedMessage(in.Destination.(encryptedMessageReflect).m, in.Source.(encryptedMessageReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalEncryptedMessage(in.MessageA.(encryptedMessageReflect).m, in.MessageB.(encryptedMessageReflect).m)}
	},
}

var messageMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeMessage(in.Message.(messageReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalMessage(in.Buf, in.Message.(messageReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalMessage(in.Message.(messageReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeMessage(in.Destination.(messageReflect).m, in.Source.(messageReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalMessage(in.MessageA.(messageReflect).m, in.MessageB.(messageReflect).m)}
	},
}

var bodyMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeBody(in.Message.(bodyReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalBody(in.Buf, in.Message.(bodyReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalBody(in.Message.(bodyReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeBody(in.Destination.(bodyReflect).m, in.Source.(bodyReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalBody(in.MessageA.(bodyReflect).m, in.MessageB.(bodyReflect).m)}
	},
}

var modeMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeMode(in.Message.(modeReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalMode(in.Buf, in.Message.(modeReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalMode(in.Message.(modeReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeMode(in.Destination.(modeReflect).m, in.Source.(modeReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalMode(in.MessageA.(modeReflect).m, in.MessageB.(modeReflect).m)}
	},
}

var rosenpassConfigMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: sizeRosenpassConfig(in.Message.(rosenpassConfigReflect).m)}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		return protoiface.MarshalOutput{Buf: marshalRosenpassConfig(in.Buf, in.Message.(rosenpassConfigReflect).m)}, nil
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := unmarshalRosenpassConfig(in.Message.(rosenpassConfigReflect).m, in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		mergeRosenpassConfig(in.Destination.(rosenpassConfigReflect).m, in.Source.(rosenpassConfigReflect).m)
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		return protoiface.EqualOutput{Equal: equalRosenpassConfig(in.MessageA.(rosenpassConfigReflect).m, in.MessageB.(rosenpassConfigReflect).m)}
	},
}

func sizeEncryptedMessage(m *EncryptedMessage) int {
	n := 0
	if m.Key != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Key))
	}
	if m.RemoteKey != "" {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.RemoteKey))
	}
	if len(m.Body) > 0 {
		n += protowire.SizeTag(4) + protowire.SizeBytes(len(m.Body))
	}
	return n
}

func marshalEncryptedMessage(b []byte, m *EncryptedMessage) []byte {
	if m.Key != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Key)
	}
	if m.RemoteKey != "" {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendString(b, m.RemoteKey)
	}
	if len(m.Body) > 0 {
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendBytes(b, m.Body)
	}
	return b
}

func unmarshalEncryptedMessage(m *EncryptedMessage, b []byte) error {
	*m = EncryptedMessage{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 2 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Key = v
			b = b[n:]
		case num == 3 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RemoteKey = v
			b = b[n:]
		case num == 4 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Body = append(m.Body[:0], v...)
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			b = b[skip:]
		}
	}
	return nil
}

func mergeEncryptedMessage(dst, src *EncryptedMessage) {
	if src.Key != "" {
		dst.Key = src.Key
	}
	if src.RemoteKey != "" {
		dst.RemoteKey = src.RemoteKey
	}
	if len(src.Body) > 0 {
		dst.Body = append(dst.Body[:0], src.Body...)
	}
}

func equalEncryptedMessage(a, b *EncryptedMessage) bool {
	if a.Key != b.Key {
		return false
	}
	if a.RemoteKey != b.RemoteKey {
		return false
	}
	if !bytes.Equal(a.Body, b.Body) {
		return false
	}
	return true
}

func sizeMessage(m *Message) int {
	n := 0
	if m.Key != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Key))
	}
	if m.RemoteKey != "" {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.RemoteKey))
	}
	if m.Body != nil {
		s := sizeBody(m.Body)
		n += protowire.SizeTag(4) + protowire.SizeBytes(s)
	}
	return n
}

func marshalMessage(b []byte, m *Message) []byte {
	if m.Key != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Key)
	}
	if m.RemoteKey != "" {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendString(b, m.RemoteKey)
	}
	if m.Body != nil {
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(sizeBody(m.Body)))
		b = marshalBody(b, m.Body)
	}
	return b
}

func unmarshalMessage(m *Message, b []byte) error {
	*m = Message{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 2 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Key = v
			b = b[n:]
		case num == 3 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RemoteKey = v
			b = b[n:]
		case num == 4 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			if m.Body == nil {
				m.Body = &Body{}
			}
			if err := unmarshalBody(m.Body, v); err != nil {
				return err
			}
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			b = b[skip:]
		}
	}
	return nil
}

func mergeMessage(dst, src *Message) {
	if src.Key != "" {
		dst.Key = src.Key
	}
	if src.RemoteKey != "" {
		dst.RemoteKey = src.RemoteKey
	}
	if src.Body != nil {
		if dst.Body == nil {
			dst.Body = &Body{}
		}
		mergeBody(dst.Body, src.Body)
	}
}

func equalMessage(a, b *Message) bool {
	if a.Key != b.Key {
		return false
	}
	if a.RemoteKey != b.RemoteKey {
		return false
	}
	if (a.Body == nil) != (b.Body == nil) {
		return false
	}
	if a.Body != nil && !equalBody(a.Body, b.Body) {
		return false
	}
	return true
}

func sizeBody(m *Body) int {
	n := 0
	if m.Type != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(m.Type))
	}
	if m.Payload != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Payload))
	}
	if m.WgListenPort != 0 {
		n += protowire.SizeTag(3) + protowire.SizeVarint(uint64(m.WgListenPort))
	}
	if m.NetBirdVersion != "" {
		n += protowire.SizeTag(4) + protowire.SizeBytes(len(m.NetBirdVersion))
	}
	if m.Mode != nil {
		s := sizeMode(m.Mode)
		n += protowire.SizeTag(5) + protowire.SizeBytes(s)
	}
	if len(m.FeaturesSupported) > 0 {
		packed := 0
		for _, v := range m.FeaturesSupported {
			packed += protowire.SizeVarint(uint64(v))
		}
		n += protowire.SizeTag(6) + protowire.SizeBytes(packed)
	}
	if m.RosenpassConfig != nil {
		s := sizeRosenpassConfig(m.RosenpassConfig)
		n += protowire.SizeTag(7) + protowire.SizeBytes(s)
	}
	if m.RelayServerAddress != nil {
		n += protowire.SizeTag(8) + protowire.SizeBytes(len(*m.RelayServerAddress))
	}
	if m.SessionId != nil {
		n += protowire.SizeTag(10) + protowire.SizeBytes(len(m.SessionId))
	}
	if m.RelayServerIP != nil {
		n += protowire.SizeTag(11) + protowire.SizeBytes(len(m.RelayServerIP))
	}
	return n
}

func marshalBody(b []byte, m *Body) []byte {
	if m.Type != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.Type))
	}
	if m.Payload != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Payload)
	}
	if m.WgListenPort != 0 {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.WgListenPort))
	}
	if m.NetBirdVersion != "" {
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendString(b, m.NetBirdVersion)
	}
	if m.Mode != nil {
		b = protowire.AppendTag(b, 5, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(sizeMode(m.Mode)))
		b = marshalMode(b, m.Mode)
	}
	if len(m.FeaturesSupported) > 0 {
		packed := 0
		for _, v := range m.FeaturesSupported {
			packed += protowire.SizeVarint(uint64(v))
		}
		b = protowire.AppendTag(b, 6, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(packed))
		for _, v := range m.FeaturesSupported {
			b = protowire.AppendVarint(b, uint64(v))
		}
	}
	if m.RosenpassConfig != nil {
		b = protowire.AppendTag(b, 7, protowire.BytesType)
		b = protowire.AppendVarint(b, uint64(sizeRosenpassConfig(m.RosenpassConfig)))
		b = marshalRosenpassConfig(b, m.RosenpassConfig)
	}
	if m.RelayServerAddress != nil {
		b = protowire.AppendTag(b, 8, protowire.BytesType)
		b = protowire.AppendString(b, *m.RelayServerAddress)
	}
	if m.SessionId != nil {
		b = protowire.AppendTag(b, 10, protowire.BytesType)
		b = protowire.AppendBytes(b, m.SessionId)
	}
	if m.RelayServerIP != nil {
		b = protowire.AppendTag(b, 11, protowire.BytesType)
		b = protowire.AppendBytes(b, m.RelayServerIP)
	}
	return b
}

func unmarshalBody(m *Body, b []byte) error {
	*m = Body{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Type = Body_Type(v)
			b = b[n:]
		case num == 2 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.Payload = v
			b = b[n:]
		case num == 3 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.WgListenPort = uint32(v)
			b = b[n:]
		case num == 4 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.NetBirdVersion = v
			b = b[n:]
		case num == 5 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			if m.Mode == nil {
				m.Mode = &Mode{}
			}
			if err := unmarshalMode(m.Mode, v); err != nil {
				return err
			}
			b = b[n:]
		case num == 6 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			for len(v) > 0 {
				item, consumed := protowire.ConsumeVarint(v)
				if consumed < 0 {
					return protowire.ParseError(consumed)
				}
				m.FeaturesSupported = append(m.FeaturesSupported, uint32(item))
				v = v[consumed:]
			}
			b = b[n:]
		case num == 6 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.FeaturesSupported = append(m.FeaturesSupported, uint32(v))
			b = b[n:]
		case num == 7 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			if m.RosenpassConfig == nil {
				m.RosenpassConfig = &RosenpassConfig{}
			}
			if err := unmarshalRosenpassConfig(m.RosenpassConfig, v); err != nil {
				return err
			}
			b = b[n:]
		case num == 8 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RelayServerAddress = &v
			b = b[n:]
		case num == 10 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.SessionId = append(m.SessionId[:0], v...)
			if m.SessionId == nil {
				m.SessionId = []byte{}
			}
			b = b[n:]
		case num == 11 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RelayServerIP = append(m.RelayServerIP[:0], v...)
			if m.RelayServerIP == nil {
				m.RelayServerIP = []byte{}
			}
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			b = b[skip:]
		}
	}
	return nil
}

func mergeBody(dst, src *Body) {
	if src.Type != 0 {
		dst.Type = src.Type
	}
	if src.Payload != "" {
		dst.Payload = src.Payload
	}
	if src.WgListenPort != 0 {
		dst.WgListenPort = src.WgListenPort
	}
	if src.NetBirdVersion != "" {
		dst.NetBirdVersion = src.NetBirdVersion
	}
	if src.Mode != nil {
		if dst.Mode == nil {
			dst.Mode = &Mode{}
		}
		mergeMode(dst.Mode, src.Mode)
	}
	if len(src.FeaturesSupported) > 0 {
		dst.FeaturesSupported = append(dst.FeaturesSupported, src.FeaturesSupported...)
	}
	if src.RosenpassConfig != nil {
		if dst.RosenpassConfig == nil {
			dst.RosenpassConfig = &RosenpassConfig{}
		}
		mergeRosenpassConfig(dst.RosenpassConfig, src.RosenpassConfig)
	}
	if src.RelayServerAddress != nil {
		v := *src.RelayServerAddress
		dst.RelayServerAddress = &v
	}
	if src.SessionId != nil {
		dst.SessionId = append(dst.SessionId[:0], src.SessionId...)
	}
	if src.RelayServerIP != nil {
		dst.RelayServerIP = append(dst.RelayServerIP[:0], src.RelayServerIP...)
	}
}

func equalBody(a, b *Body) bool {
	if a.Type != b.Type {
		return false
	}
	if a.Payload != b.Payload {
		return false
	}
	if a.WgListenPort != b.WgListenPort {
		return false
	}
	if a.NetBirdVersion != b.NetBirdVersion {
		return false
	}
	if (a.Mode == nil) != (b.Mode == nil) {
		return false
	}
	if a.Mode != nil && !equalMode(a.Mode, b.Mode) {
		return false
	}
	if len(a.FeaturesSupported) != len(b.FeaturesSupported) {
		return false
	}
	for i := range a.FeaturesSupported {
		if a.FeaturesSupported[i] != b.FeaturesSupported[i] {
			return false
		}
	}
	if (a.RosenpassConfig == nil) != (b.RosenpassConfig == nil) {
		return false
	}
	if a.RosenpassConfig != nil && !equalRosenpassConfig(a.RosenpassConfig, b.RosenpassConfig) {
		return false
	}
	if (a.RelayServerAddress == nil) != (b.RelayServerAddress == nil) {
		return false
	}
	if a.RelayServerAddress != nil && *a.RelayServerAddress != *b.RelayServerAddress {
		return false
	}
	if (a.SessionId == nil) != (b.SessionId == nil) {
		return false
	}
	if !bytes.Equal(a.SessionId, b.SessionId) {
		return false
	}
	if (a.RelayServerIP == nil) != (b.RelayServerIP == nil) {
		return false
	}
	if !bytes.Equal(a.RelayServerIP, b.RelayServerIP) {
		return false
	}
	return true
}

func sizeMode(m *Mode) int {
	n := 0
	if m.Direct != nil {
		n += protowire.SizeTag(1) + protowire.SizeVarint(protowire.EncodeBool(*m.Direct))
	}
	return n
}

func marshalMode(b []byte, m *Mode) []byte {
	if m.Direct != nil {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, protowire.EncodeBool(*m.Direct))
	}
	return b
}

func unmarshalMode(m *Mode, b []byte) error {
	*m = Mode{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.VarintType:
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			x := protowire.DecodeBool(v)
			m.Direct = &x
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			b = b[skip:]
		}
	}
	return nil
}

func mergeMode(dst, src *Mode) {
	if src.Direct != nil {
		v := *src.Direct
		dst.Direct = &v
	}
}

func equalMode(a, b *Mode) bool {
	if (a.Direct == nil) != (b.Direct == nil) {
		return false
	}
	if a.Direct != nil && *a.Direct != *b.Direct {
		return false
	}
	return true
}

func sizeRosenpassConfig(m *RosenpassConfig) int {
	n := 0
	if len(m.RosenpassPubKey) > 0 {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.RosenpassPubKey))
	}
	if m.RosenpassServerAddr != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.RosenpassServerAddr))
	}
	return n
}

func marshalRosenpassConfig(b []byte, m *RosenpassConfig) []byte {
	if len(m.RosenpassPubKey) > 0 {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, m.RosenpassPubKey)
	}
	if m.RosenpassServerAddr != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.RosenpassServerAddr)
	}
	return b
}

func unmarshalRosenpassConfig(m *RosenpassConfig, b []byte) error {
	*m = RosenpassConfig{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		b = b[n:]
		switch {
		case num == 1 && typ == protowire.BytesType:
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RosenpassPubKey = append(m.RosenpassPubKey[:0], v...)
			b = b[n:]
		case num == 2 && typ == protowire.BytesType:
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return protowire.ParseError(n)
			}
			m.RosenpassServerAddr = v
			b = b[n:]
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			b = b[skip:]
		}
	}
	return nil
}

func mergeRosenpassConfig(dst, src *RosenpassConfig) {
	if len(src.RosenpassPubKey) > 0 {
		dst.RosenpassPubKey = append(dst.RosenpassPubKey[:0], src.RosenpassPubKey...)
	}
	if src.RosenpassServerAddr != "" {
		dst.RosenpassServerAddr = src.RosenpassServerAddr
	}
}

func equalRosenpassConfig(a, b *RosenpassConfig) bool {
	if !bytes.Equal(a.RosenpassPubKey, b.RosenpassPubKey) {
		return false
	}
	if a.RosenpassServerAddr != b.RosenpassServerAddr {
		return false
	}
	return true
}
