// Code generated by go run ./tools/protoc-gen-go-netbird-tinygo -target signal; DO NOT EDIT.

//go:build tinygo

package proto

import "google.golang.org/protobuf/reflect/protoreflect"

func encryptedMessageProtoReflect(m *EncryptedMessage) protoreflect.Message {
	return encryptedMessageReflect{m: m}
}

func messageProtoReflect(m *Message) protoreflect.Message {
	return messageReflect{m: m}
}

func bodyProtoReflect(m *Body) protoreflect.Message {
	return bodyReflect{m: m}
}

func modeProtoReflect(m *Mode) protoreflect.Message {
	return modeReflect{m: m}
}

func rosenpassConfigProtoReflect(m *RosenpassConfig) protoreflect.Message {
	return rosenpassConfigReflect{m: m}
}
